// `schema/`, `migrate/` and `seed/` are deliberately absent: they are reached by path,
// and nothing outside this package may name a table.
export {
  BaseRepository,
  Database,
  DatabaseCluster,
  type DatabaseConfig,
  type DatabaseStats,
  type DrizzleClient,
  KeysetCursor,
  type ReplicaHealth,
  type ShardConfig,
} from "./primitive/index.js";
export {
  PgAccountRepository,
  PgActivityLogger,
  PgApiKeyRepository,
  PgBootstrapMembershipEnroller,
  PgCapabilityRepository,
  PgDocGrantRepository,
  PgDocPageRepository,
  PgDocSpaceRepository,
  PgEntitlementRepository,
  PgFlagRepository,
  PgInvitationClaimer,
  PgInvitationRepository,
  PgMaintenanceGateway,
  PgMemberRepository,
  PgMembershipReader,
  PgNotificationPreferenceRepository,
  PgNotificationRecipientReader,
  PgNotificationRepository,
  PgOrganizationFounder,
  PgOrganizationReader,
  PgOutboxGateway,
  PgOutboxPublisher,
  PgPartitionArchiveGateway,
  PgPermissionOverrideRepository,
  PgPersonalOrganizationEnroller,
  PgPlatformPolicyRepository,
  PgPlatformReader,
  PgRoleRepository,
  PgShardMapReader,
  PgShardResolver,
  PgTenantRepository,
  PgUserReader,
  PgVectorStore,
} from "./repository/index.js";
export {
  type OpenTransaction,
  PgUnitOfWork,
  type PgUnitOfWorkConfig,
  type PlacedShard,
  ShardScope,
  TransactionScope,
} from "./transaction/index.js";
