export const doc = {
  // ── reading ──
  "doc.home.title": "Docs",
  "doc.home.description": "Guides and reference for this organization.",
  "doc.home.public": "Documentation",
  "doc.home.manage": "Manage docs",
  "doc.back.app": "Back to the app",
  "doc.back.home": "Home",
  "doc.home.empty": "There are no docs here yet.",
  "doc.space.empty": "Nothing in this space has been published yet.",
  "doc.nav.label": "Documentation",
  "doc.nav.expand": "Expand",
  "doc.nav.collapse": "Collapse",
  "doc.sidebar.open": "Open navigation",
  "doc.sidebar.close": "Close navigation",
  "doc.switcher.label": "Documentation space",
  "doc.toc.title": "On this page",
  "doc.copy.markdown": "Copy Markdown",
  "doc.copy.copied": "Copied",
  "doc.code.copy": "Copy",
  "doc.code.copied": "Copied",
  "doc.open.label": "Open",
  "doc.open.markdown": "View as Markdown",
  "doc.open.edit": "Edit this page",
  "doc.updated": "Last published {date}",
  "doc.appearance.mode": "Colour mode",
  "doc.appearance.light": "Light",
  "doc.appearance.dark": "Dark",
  "doc.appearance.theme": "Theme",

  // ── search ──
  "doc.search.label": "Search documentation",
  "doc.search.placeholder": "Search",
  // Keyboard names are not translated: the key cap says Ctrl in every locale.
  "doc.search.shortcut": "Ctrl K",
  "doc.search.empty": "Nothing matches that search.",
  "doc.search.loading": "Searching…",
  "doc.search.pages": "Pages",
  "doc.search.sections": "In the text",
  "doc.search.inSpace": "In {space}",

  // ── managing spaces ──
  "doc.manage.title": "Manage docs",
  "doc.manage.description": "Spaces group pages into one sidebar. Each has its own address.",
  "doc.manage.spaces": "Spaces",
  "doc.manage.new": "New space",
  "doc.manage.empty": "No spaces yet. Create the first one below.",
  "doc.manage.pages": "Pages",
  "doc.space.slug": "Address",
  "doc.space.slugHint": "Lower-case letters, numbers and hyphens. It becomes the space's URL.",
  "doc.space.title": "Title",
  "doc.space.description": "Description",
  "doc.space.icon": "Icon",
  "doc.space.iconNone": "No icon",
  "doc.space.audience": "Who can read it",
  "doc.space.audience.members": "Members of this organization",
  // Nobody else sees that the space exists, an administrator included.
  "doc.space.audience.owner": "Only me",
  "doc.space.audience.public": "Anyone, signed in or not",
  "doc.space.audience.granted": "Only the organizations, people and plans granted access",
  // Said beside the choice, because the obvious misreading is that a tenant can publish.
  "doc.space.audience.hint": "Public and granted spaces are for the platform's own docs.",
  "doc.space.theme": "Opens in theme",
  "doc.space.themeNone": "The reader's own choice",
  "doc.space.create": "Create space",
  "doc.space.save": "Save space",
  "doc.space.saved": "Space saved.",
  "doc.space.delete": "Delete space",
  "doc.space.deleteConfirm": "Delete {title} and every page in it",
  "doc.space.open": "Read",
  "doc.space.edit": "Pages",

  // ── the page tree ──
  "doc.tree.empty": "No pages yet. Add the first one.",
  "doc.tree.add": "Add",
  "doc.tree.addUnder": "Add under {title}",
  "doc.tree.moveUp": "Move {title} up",
  "doc.tree.moveDown": "Move {title} down",
  "doc.tree.indent": "Move {title} under the one above",
  "doc.tree.outdent": "Move {title} out one level",
  "doc.tree.delete": "Delete {title}",
  "doc.tree.deleteConfirm": "Delete {title} and everything under it",
  "doc.page.kind": "Kind",
  "doc.page.kind.page": "Page",
  "doc.page.kind.section": "Section heading",
  "doc.page.kind.link": "External link",
  "doc.page.status.draft": "Draft",
  "doc.page.status.published": "Published",
  "doc.page.status.changed": "Unpublished changes",

  // ── the editor ──
  "doc.editor.title": "Edit page",
  "doc.editor.fields": "Page details",
  "doc.page.title": "Title",
  "doc.page.slug": "Address",
  "doc.page.description": "Description",
  "doc.page.icon": "Icon",
  "doc.page.url": "Link address",
  "doc.page.markdown": "Content",
  "doc.page.markdownHint":
    'Markdown. `> [!NOTE]` makes a callout; `::::cards` with `:::card{title="…" href="…"}` inside makes a card grid.',
  "doc.editor.write": "Write",
  "doc.editor.preview": "Preview",
  "doc.editor.previewEmpty": "Nothing to preview yet.",
  "doc.editor.save": "Save draft",
  "doc.editor.saving": "Saving…",
  "doc.editor.saved": "Draft saved.",
  "doc.editor.unsaved": "Unsaved changes",
  "doc.editor.publish": "Publish",
  "doc.editor.published": "Published as revision {revision}.",
  "doc.editor.structural":
    "Sections and links have no content to publish: they appear as soon as they are saved.",
  "doc.editor.view": "View the live page",
  "doc.editor.image": "Insert image",
  "doc.editor.imageUploading": "Uploading image…",
  "doc.editor.imageTooLarge": "Images can be at most 5 MB.",
  "doc.editor.imageType": "Use a PNG, JPEG, WebP, GIF or AVIF image.",
  "doc.editor.back": "All pages",

  // ── private access ──
  "doc.grant.title": "Who can read it",
  "doc.grant.description":
    "Open this space to an organization, one person, or every organization on a plan.",
  "doc.grant.none": "Nobody outside the platform has been given access yet.",
  "doc.grant.kind": "Grant to",
  "doc.grant.kind.organization": "An organization",
  "doc.grant.kind.user": "A person",
  "doc.grant.kind.plan": "Everyone on a plan",
  "doc.grant.target": "Who",
  "doc.grant.target.organization": "The organization's address or id",
  "doc.grant.target.user": "Their email address",
  "doc.grant.target.plan": "The plan's key",
  "doc.grant.reason": "Reason",
  "doc.grant.reasonHint": "Say why, so whoever reviews this later knows whether it can go.",
  "doc.grant.expires": "Ends on",
  "doc.grant.expiresHint": "Leave empty to keep it until it is revoked.",
  "doc.grant.save": "Grant access",
  "doc.grant.revoke": "Revoke",
  "doc.grant.expiresOn": "until {date}",
  "doc.grant.expired": "expired",
  "doc.grant.forever": "no end date",

  // ── history ──
  "doc.revision.title": "History",
  "doc.revision.none": "Not published yet.",
  "doc.revision.item": "Revision {revision}",
  "doc.revision.restore": "Restore to draft",
  "doc.revision.restored": "Revision {revision} is now the draft. Publish it to make it live.",
  "doc.access.legend": "Access",
  "doc.access.hint":
    "Readers see this only when every link set here passes. Leave all four as None for no link.",
  "doc.access.spaceHint":
    "Every page in the space follows these links, and a page can add its own.",
  "doc.access.module": "Module",
  "doc.access.permission": "Permission",
  "doc.access.flag": "Feature flag",
  "doc.access.plan": "Plan",
  "doc.access.none": "None",
  "doc.access.unknown":
    "This links to {key}, which no longer exists, so nobody can read it until it is changed.",
  "doc.tree.linked": "Linked to a feature",
  "doc.space.repository": "Repository URL",
  "doc.space.repositoryHint": "An https link shown in the reader's sidebar. Leave empty for none.",
} as const;
