// The graph explorer: the canvas, its sidebar and the panel beside it.
export const graph = {
  "graph.title": "Graph",
  "graph.loading": "Loading the graph…",
  "graph.failed": "The graph could not be loaded.",
  "graph.unsupported": "This graph was made by a newer analyzer. Scan again to view it.",
  "graph.roles": "{framework} files by role",
  "graph.roles.any": "Files by role",
  "graph.roles.hint": "Click a role to highlight its files; click it again to clear.",
  "graph.filter.folder": "Folder",
  "graph.filter.repository": "Repository",
  "graph.filter.all": "All",
  "graph.depth": "Group depth",
  "graph.folder.counts": "{files} files · in {in} · out {out}",
  "graph.file.counts": "in {in} · out {out}",
  "graph.expand": "Expand",
  "graph.collapse": "Collapse",
  "graph.partial":
    "Graph is partial: {resolved} of {total} imports into this repository resolved ({percent}%)",
  "graph.partial.show": "Show what did not resolve",
  "graph.partial.hide": "Hide",
  "graph.tab.overview": "Overview",
  "graph.tab.ask": "Ask",
  "graph.ask.soon":
    "Ask arrives with the next phase: questions about this graph, answered with citations.",
  "graph.overview.repositories": "Repositories",
  "graph.overview.frameworks": "Frameworks",
  "graph.overview.files": "Files",
  "graph.overview.imports": "Imports",
  "graph.overview.importsHere": "{count} between files here",
  "graph.overview.routes": "Routes",
  "graph.overview.showAll": "Show all {count}",
  "graph.overview.showFewer": "Show fewer",
  "graph.overview.mostDepended": "Most depended on",
  "graph.overview.importers": "{count} files import it",
  "graph.detail.close": "Close",
  "graph.detail.role": "Role",
  "graph.detail.lines": "{count} lines",
  "graph.detail.imports": "Imports",
  "graph.detail.dependents": "Imported by",
  "graph.detail.routes": "Routes defined here",
  "graph.detail.none": "None",
  "graph.detail.impact": "Show impact",
  "graph.detail.impactOff": "Hide impact",
  "graph.detail.impactCount": "{count} files depend on this, directly or not",
  "graph.search": "Search files, exports and routes",
  "graph.search.empty": "Nothing matches.",
  "graph.search.files": "Files",
  "graph.search.exports": "Exports",
  "graph.search.routes": "Routes",
  "graph.scan": "Scan",
  "graph.scan.latest": "Latest",
  "graph.view.save": "Save view",
  "graph.view.name": "View name",
  "graph.view.saved": "Saved views",
  "graph.view.remove": "Remove",
  "graph.view.none": "No saved views yet.",
  "insight.title": "Insights",
  "insight.intro": "What the latest scan found. Every path opens in the graph.",
  "insight.mostDepended": "Most depended on",
  "insight.mostDepended.hint": "A change to these reaches the most files.",
  "insight.cycles": "Import cycles",
  "insight.cycles.hint": "Files that import each other, directly or through others.",
  "insight.cycles.none": "No cycles.",
  "insight.unusedFiles": "Unused files",
  "insight.unusedFiles.hint": "Nothing that starts the app reaches these.",
  "insight.unusedExports": "Unused exports",
  "insight.unusedExports.hint": "Exported, and imported by name nowhere.",
  "insight.unguarded": "Routes without a guard",
  "insight.unguarded.hint": "No guard or authentication middleware was found on these.",
  "insight.none": "Nothing here.",
  "insight.more": "{count} more",
  "insight.openInGraph": "Open in graph",
  "impact.title": "Change impact",
  "impact.intro": "Pick a file to see everything that depends on it, and the routes it reaches.",
  "impact.pick": "File",
  "impact.placeholder": "Start typing a path",
  "impact.depth": "{count} files at distance {depth}",
  "impact.total": "{count} files depend on {path}",
  "impact.routes": "Routes affected",
  "impact.routes.none": "No route's handler depends on it.",
  "compare.title": "Compare",
  "compare.intro": "What changed between two scans of this project.",
  "compare.before": "Before",
  "compare.after": "After",
  "compare.pick": "Pick two scans that succeeded.",
  "compare.files": "Files",
  "compare.edges": "Imports",
  "compare.routes": "Routes",
  "compare.cyclesIntroduced": "Cycles introduced",
  "compare.cyclesFixed": "Cycles fixed",
  "compare.added": "{count} added",
  "compare.removed": "{count} removed",
  "compare.same": "No change.",
} as const;
