// Projects: repositories grouped into one graph, and who may see it.
export const project = {
  "project.title": "Projects",
  "project.intro": "Each project is one or more repositories scanned into a single graph.",
  "project.new": "New project",
  "project.empty": "No projects yet.",
  "project.empty.description": "Connect GitHub and pick the repositories that make up your app.",
  "project.repositoryCount": "{count} repositories",
  "project.visibility": "Who can see it",
  "project.visibility.org": "Everyone in the organization",
  "project.visibility.restricted": "Only people and teams given access",
  "project.defaultRole": "Role for everyone",
  "project.role.project_admin": "Project admin",
  "project.role.project_editor": "Editor",
  "project.role.project_viewer": "Viewer",
  "project.name": "Name",
  "project.slug": "URL name",
  "project.slug.hint": "Lowercase letters, digits and dashes.",
  "project.description": "Description",
  "project.create": "Create project",
  "project.slugTaken": "Another project already uses that URL name.",
  "project.github.title": "GitHub",
  "project.github.connect": "Connect GitHub",
  "project.github.connectMore": "Add another account",
  "project.github.connected": "GitHub connected.",
  "project.github.failed": "GitHub could not be connected. Try again from this page.",
  "project.github.unconfigured":
    "This deployment has no GitHub App configured, so repositories cannot be connected yet.",
  "project.github.none": "Connect GitHub to choose repositories.",
  "project.github.suspended": "suspended",
  "project.repositories": "Repositories",
  "project.repositories.pick": "Pick the repositories that make up this project.",
  "project.repositories.none": "The connected accounts have no repositories this app can read.",
  "project.repositories.private": "private",
  "project.repositories.branches": "Branches",
  "project.repositories.branches.hint": "Comma separated. Pushes to these are scanned.",
  "project.repositories.rootPath": "Folder",
  "project.repositories.rootPath.hint": "For a monorepo: the folder the app lives in.",
  "project.repositories.add": "Add repository",
  "project.repositories.remove": "Remove",
  "project.settings": "Settings",
  "project.overview": "Overview",
  "project.settings.general": "General",
  "project.settings.analysis": "Analysis",
  "project.settings.access": "Access",
  "project.settings.danger": "Delete",
  "project.settings.save": "Save",
  "project.settings.saved": "Saved.",
  "project.schedule": "Scheduled scans",
  "project.schedule.off": "Off",
  "project.schedule.daily": "Daily",
  "project.schedule.weekly": "Weekly",
  "project.ignore": "Ignored paths",
  "project.ignore.hint": "One glob per line, as in .gitignore.",
  "project.tsconfigPath": "tsconfig path",
  "project.workspace": "Workspace",
  "project.access.intro": "Who can open this project, and with what role.",
  "project.access.orgDefault": "Everyone in the organization gets {role}.",
  "project.access.restricted": "Only the people and teams below can open it.",
  "project.access.grantee": "Person or team",
  "project.access.role": "Role",
  "project.access.grant": "Give access",
  "project.access.revoke": "Remove",
  "project.access.empty": "No one has been given access directly.",
  "project.access.kind.user": "Person",
  "project.access.kind.team": "Team",
  "project.delete": "Delete project",
  "project.delete.description":
    "Its graphs, scans and settings are removed. The audit log keeps a record.",
  "project.delete.confirm": "Type {name} to confirm.",
  "project.overview.noScans": "No scans yet",
  "project.overview.noScans.description":
    "Scans arrive with the next phase of wiremap. Repositories are connected and ready.",
  "project.accessOverview.title": "Project access",
  "project.accessOverview.intro":
    "Who can open each project, and the role they get. Hover a cell to see where it comes from.",
  "project.accessOverview.empty": "No projects yet.",
  "project.accessOverview.none": "No access",
  "project.accessOverview.via.organization": "Their organization role reads every project",
  "project.accessOverview.via.default": "Everyone in the organization gets this role",
  "project.accessOverview.via.direct": "Given directly",
  "project.accessOverview.via.team": "Through the team {team}",
  "project.notFound": "This project does not exist or you cannot see it.",
} as const;
