export const webhook = {
  "webhook.title": "Webhooks",
  "webhook.intro":
    "Send scan results and new findings to your own endpoint or a Slack channel. Each delivery is retried for a while; twenty failures in a row switch a webhook off.",
  "webhook.empty": "No webhooks yet.",
  "webhook.add": "Add webhook",
  "webhook.kind": "Kind",
  "webhook.kind.generic": "Endpoint",
  "webhook.kind.slack": "Slack",
  "webhook.url": "URL",
  "webhook.url.hint.generic": "An https URL that accepts a JSON POST.",
  "webhook.url.hint.slack": "A Slack incoming webhook URL, from your Slack app's settings.",
  "webhook.project": "Project",
  "webhook.project.all": "Every project",
  "webhook.events": "Events",
  "webhook.event.scan.succeeded": "Scan succeeded",
  "webhook.event.scan.failed": "Scan failed",
  "webhook.event.finding.created": "New finding",
  "webhook.secret.title": "Signing secret",
  "webhook.secret.body":
    "Copy it now: it is not shown again. Each delivery carries X-Wiremap-Signature, an HMAC-SHA256 of the timestamp, a dot and the body.",
  "webhook.secret.done": "Done",
  "webhook.status.active": "Active",
  "webhook.status.off": "Off after repeated failures",
  "webhook.status.last": "Last: {status}",
  "webhook.status.never": "Not sent yet",
  "webhook.status.failures": "{count} failures in a row",
  "webhook.test": "Send test",
  "webhook.test.ok": "Delivered ({status}).",
  "webhook.test.failed": "Not delivered ({status}).",
  "webhook.test.noResponse": "no response",
  "webhook.enable": "Turn back on",
  "webhook.remove": "Remove",
  "webhook.failed": "That did not save. Check the URL and try again.",
} as const;
