// Generated by build-sprite.mjs. Do not edit.
export const ICON_NAMES = [
  "bell",
  "book",
  "chat",
  "check",
  "chevron-down",
  "chevron-right",
  "chevron-up-down",
  "clock",
  "copy",
  "edit",
  "external",
  "file",
  "hash",
  "key",
  "menu",
  "moon",
  "rocket",
  "search",
  "sun",
  "user",
  "x",
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export class IconRegistry {
  private constructor() {}

  public static all(): readonly IconName[] {
    return ICON_NAMES;
  }

  public static isKnown(value: string): value is IconName {
    return (ICON_NAMES as readonly string[]).includes(value);
  }
}
