// Generated by build-sprite.mjs. Do not edit.
export const ICON_NAMES = [
  "activity",
  "bell",
  "book",
  "branch",
  "chat",
  "check",
  "chevron-down",
  "chevron-right",
  "chevron-up-down",
  "clock",
  "comment",
  "copy",
  "edit",
  "external",
  "file",
  "folder",
  "github",
  "graph",
  "hash",
  "key",
  "layers",
  "logout",
  "menu",
  "monitor",
  "moon",
  "pin",
  "play",
  "plus",
  "rocket",
  "route",
  "search",
  "settings",
  "shield",
  "sparkle",
  "sun",
  "team",
  "user",
  "webhook",
  "x",
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export class IconRegistry {
  private constructor() {}

  public static all(): readonly IconName[] {
    return ICON_NAMES;
  }

  public static isKnown(value: string): value is IconName {
    return (ICON_NAMES as readonly string[]).includes(value);
  }
}
