import type { NamespaceBundle } from "../namespace.js";

// Total, not partial: `NamespaceBundle` is a `Record`, so an `en` key added without a
// translation fails `tsc` rather than rendering an English sentence on a Bengali page.
export const account: NamespaceBundle<"account"> = {
  "account.profile": "প্রোফাইল",
  "account.name": "আপনার নাম",
  "account.saveChanges": "পরিবর্তন সংরক্ষণ করুন",
  "account.saved": "সংরক্ষিত হয়েছে।",
  "account.changePassword": "পাসওয়ার্ড পরিবর্তন করুন",
  "account.currentPassword": "বর্তমান পাসওয়ার্ড",
  "account.resetNewPassword": "নতুন পাসওয়ার্ড",
  "account.changePasswordDone": "আপনার পাসওয়ার্ড পরিবর্তিত হয়েছে। অন্য ডিভাইসগুলি সাইন আউট হয়ে গেছে।",
  "account.changePasswordFailed": "বর্তমান পাসওয়ার্ডটি সঠিক ছিল না।",
  "account.changeEmail": "ইমেইল ঠিকানা পরিবর্তন করুন",
  "account.newEmail": "নতুন ইমেইল ঠিকানা",
  "account.changeEmailSent":
    "আপনার বর্তমান ঠিকানায় একটি নিশ্চিতকরণ পাঠানো হয়েছে। সেখানে অনুমোদন করলে পরিবর্তনটি কার্যকর হবে।",
  "account.twoFactorTitle": "দুই-ধাপ প্রমাণীকরণ",
  "account.twoFactorOff": "বন্ধ। এই অ্যাকাউন্টের একমাত্র সুরক্ষা আপনার পাসওয়ার্ড।",
  "account.twoFactorOn": "চালু। সাইন ইন করার সময় আপনার কাছে একটি কোড চাওয়া হবে।",
  "account.twoFactorEnable": "দুই-ধাপ প্রমাণীকরণ চালু করুন",
  "account.twoFactorDisable": "দুই-ধাপ প্রমাণীকরণ বন্ধ করুন",
  "account.twoFactorConfirmPassword": "চালিয়ে যেতে আপনার পাসওয়ার্ড নিশ্চিত করুন",
  "account.twoFactorScan": "আপনার অথেন্টিকেটর অ্যাপ দিয়ে এটি স্ক্যান করুন।",
  "account.twoFactorManual": "স্ক্যান করতে পারছেন না? বদলে এই কীটি হাতে লিখুন।",
  "account.twoFactorVerifyPrompt": "শেষ করতে আপনার অ্যাপে এখন যে কোডটি দেখাচ্ছে সেটি লিখুন।",
  "account.twoFactorEnabled": "দুই-ধাপ প্রমাণীকরণ চালু আছে।",
  "account.twoFactorDisabled": "দুই-ধাপ প্রমাণীকরণ বন্ধ আছে।",
  "account.twoFactorCode": "প্রমাণীকরণ কোড",
  "account.twoFactorFailed": "কোডটি সঠিক ছিল না।",
  "account.backupCodes": "ব্যাকআপ কোড",
  "account.backupCodesHint":
    "এগুলি নিরাপদ জায়গায় সংরক্ষণ করুন। ফোন হারালে প্রতিটি কোড একবার সাইন ইন করাবে, এবং কেবল এখনই এগুলি দেখানো হচ্ছে।",
  "account.backupCodesRegenerate": "নতুন ব্যাকআপ কোড তৈরি করুন",
  "account.backupCodesRegenerated": "নতুন কোড তৈরি হয়েছে। পুরনোগুলি আর কাজ করবে না।",
  "account.linkedAccounts": "সংযুক্ত অ্যাকাউন্ট",
  "account.linkedAccountsHint": "এই অ্যাকাউন্টে সাইন ইন করার অন্যান্য উপায়।",
  "account.linkGoogle": "একটি Google অ্যাকাউন্ট সংযুক্ত করুন",
  "account.unlink": "সংযোগ বিচ্ছিন্ন করুন",
  "account.unlinkLast": "এটিই আপনার সাইন ইন করার একমাত্র উপায়, তাই এটি বিচ্ছিন্ন করা যাবে না।",
  "account.socialFailed": "সাইন ইন সম্পূর্ণ হয়নি।",
  "account.sessions": "আপনি যেখানে সাইন ইন আছেন",
  "account.sessionCurrent": "এই ডিভাইস",
  "account.sessionRevoke": "সাইন আউট",
  "account.signOutEverywhere": "সব ডিভাইসে সাইন আউট করুন",
  "account.signOutEverywhereDone": "অন্য প্রতিটি ডিভাইস সাইন আউট হয়ে গেছে।",
};
