import type { NamespaceBundle } from "../namespace.js";

// Total, not partial: `NamespaceBundle` is a `Record`, so an `en` key added without a
// translation fails `tsc` rather than rendering an English sentence on a Bengali page.
export const auth: NamespaceBundle<"auth"> = {
  "auth.signIn": "সাইন ইন",
  "auth.signingIn": "সাইন ইন করা হচ্ছে…",
  "auth.email": "ইমেইল",
  "auth.password": "পাসওয়ার্ড",
  "auth.signInFailed": "ইমেইল ও পাসওয়ার্ড মেলেনি।",
  "auth.forgotPassword": "পাসওয়ার্ড ভুলে গেছেন?",
  "auth.noAccount": "এখনও অ্যাকাউন্ট নেই?",
  "auth.haveAccount": "আগে থেকেই অ্যাকাউন্ট আছে?",
  "auth.signUp": "অ্যাকাউন্ট তৈরি করুন",
  "auth.signingUp": "আপনার অ্যাকাউন্ট তৈরি করা হচ্ছে…",
  "auth.name": "আপনার নাম",
  "auth.confirmPassword": "পাসওয়ার্ড নিশ্চিত করুন",
  "auth.passwordMismatch": "পাসওয়ার্ড দুটি মেলেনি।",
  "auth.passwordTooShort": "কমপক্ষে ১২টি অক্ষর ব্যবহার করুন।",
  "auth.emailTaken": "এই ইমেইলে ইতিমধ্যে একটি অ্যাকাউন্ট আছে। সাইন ইন করে দেখুন।",
  "auth.signUpFailed": "অ্যাকাউন্টটি তৈরি করা যায়নি।",
  "auth.verifyEmail": "আপনার ইমেইল ঠিকানা নিশ্চিত করতে ইনবক্স দেখুন।",
  "auth.verifyEmailSent": "{email} ঠিকানায় একটি লিঙ্ক পাঠানো হয়েছে। অ্যাকাউন্ট তৈরি সম্পূর্ণ করতে সেটি খুলুন।",
  "auth.verifyEmailResend": "আবার পাঠান",
  "auth.verifyEmailResent": "পাঠানো হয়েছে। এক মিনিট অপেক্ষা করুন, তারপর স্প্যাম ফোল্ডার দেখুন।",
  "auth.verifyEmailDone": "আপনার ইমেইল ঠিকানা নিশ্চিত হয়েছে। এখন সাইন ইন করতে পারেন।",
  "auth.verifyEmailFailed": "লিঙ্কটির মেয়াদ শেষ হয়ে গেছে অথবা এটি আগেই ব্যবহৃত হয়েছে।",
  "auth.resetRequest": "পুনঃনির্ধারণের লিঙ্ক পাঠান",
  "auth.resetSent": "ওই ইমেইলে অ্যাকাউন্ট থাকলে একটি লিঙ্ক পাঠানো হয়েছে।",
  "auth.resetTitle": "নতুন পাসওয়ার্ড বেছে নিন",
  "auth.resetNewPassword": "নতুন পাসওয়ার্ড",
  "auth.resetSubmit": "এই পাসওয়ার্ডটি সংরক্ষণ করুন",
  "auth.resetDone": "আপনার পাসওয়ার্ড সংরক্ষিত হয়েছে। এটি দিয়ে সাইন ইন করুন।",
  "auth.resetFailed": "লিঙ্কটির মেয়াদ শেষ হয়ে গেছে অথবা এটি আগেই ব্যবহৃত হয়েছে।",
  "auth.twoFactorCode": "প্রমাণীকরণ কোড",
  "auth.twoFactorHint": "আপনার অথেন্টিকেটর অ্যাপের ছয়-অঙ্কের কোডটি লিখুন।",
  "auth.twoFactorUseBackup": "বদলে একটি ব্যাকআপ কোড ব্যবহার করুন",
  "auth.twoFactorUseTotp": "বদলে আপনার অথেন্টিকেটর অ্যাপ ব্যবহার করুন",
  "auth.twoFactorUseOtp": "বদলে আমাকে ইমেইলে কোড পাঠান",
  "auth.twoFactorBackupCode": "ব্যাকআপ কোড",
  "auth.twoFactorBackupHint": "প্রতিটি ব্যাকআপ কোড একবারই কাজ করে। যেটি ব্যবহার করেননি সেটি লিখুন।",
  "auth.twoFactorOtpSend": "আমার ইমেইলে কোড পাঠান",
  "auth.twoFactorOtpSent": "আপনার ইমেইল ঠিকানায় একটি কোড পাঠানো হয়েছে। এটি পাঁচ মিনিট পরে মেয়াদোত্তীর্ণ হবে।",
  "auth.twoFactorFailed": "কোডটি সঠিক ছিল না।",
  "auth.continueWithGoogle": "Google দিয়ে চালিয়ে যান",
  "auth.orDivider": "অথবা",
  "auth.socialFailed": "সাইন ইন সম্পূর্ণ হয়নি।",
};
