import type { NamespaceBundle } from "../namespace.js";

export const doc: NamespaceBundle<"doc"> = {
  "doc.home.title": "ডক",
  "doc.home.description": "এই প্রতিষ্ঠানের নির্দেশিকা ও রেফারেন্স।",
  "doc.home.public": "ডকুমেন্টেশন",
  "doc.home.manage": "ডক পরিচালনা",
  "doc.back.app": "অ্যাপে ফিরে যান",
  "doc.back.home": "হোম",
  "doc.home.empty": "এখানে এখনও কোনো ডক নেই।",
  "doc.space.empty": "এই স্পেসে এখনও কিছু প্রকাশিত হয়নি।",
  "doc.nav.label": "ডকুমেন্টেশন",
  "doc.nav.expand": "প্রসারিত করুন",
  "doc.nav.collapse": "সংকুচিত করুন",
  "doc.sidebar.open": "নেভিগেশন খুলুন",
  "doc.sidebar.close": "নেভিগেশন বন্ধ করুন",
  "doc.switcher.label": "ডকুমেন্টেশন স্পেস",
  "doc.toc.title": "এই পাতায়",
  "doc.copy.markdown": "মার্কডাউন কপি করুন",
  "doc.copy.copied": "কপি হয়েছে",
  "doc.code.copy": "কপি",
  "doc.code.copied": "কপি হয়েছে",
  "doc.open.label": "খুলুন",
  "doc.open.markdown": "মার্কডাউন হিসেবে দেখুন",
  "doc.open.edit": "এই পাতা সম্পাদনা করুন",
  "doc.updated": "সর্বশেষ প্রকাশিত {date}",
  "doc.appearance.mode": "রঙের মোড",
  "doc.appearance.light": "আলো",
  "doc.appearance.dark": "অন্ধকার",
  "doc.appearance.theme": "থিম",

  "doc.search.label": "ডকুমেন্টেশন খুঁজুন",
  "doc.search.placeholder": "খুঁজুন",
  "doc.search.shortcut": "Ctrl K",
  "doc.search.empty": "এই অনুসন্ধানে কিছু মেলেনি।",
  "doc.search.loading": "খোঁজা হচ্ছে…",
  "doc.search.pages": "পাতা",
  "doc.search.sections": "লেখার ভেতরে",

  "doc.manage.title": "ডক পরিচালনা",
  "doc.manage.description": "স্পেস পাতাগুলোকে একটি সাইডবারে সাজায়। প্রতিটির নিজস্ব ঠিকানা আছে।",
  "doc.manage.spaces": "স্পেস",
  "doc.manage.new": "নতুন স্পেস",
  "doc.manage.empty": "এখনও কোনো স্পেস নেই। নিচে প্রথমটি তৈরি করুন।",
  "doc.manage.pages": "পাতা",
  "doc.space.slug": "ঠিকানা",
  "doc.space.slugHint": "ছোট হাতের অক্ষর, সংখ্যা ও হাইফেন। এটিই স্পেসের URL হবে।",
  "doc.space.title": "শিরোনাম",
  "doc.space.description": "বিবরণ",
  "doc.space.icon": "আইকন",
  "doc.space.iconNone": "কোনো আইকন নয়",
  "doc.space.audience": "কারা পড়তে পারবে",
  "doc.space.audience.members": "এই প্রতিষ্ঠানের সদস্যরা",
  "doc.space.audience.public": "যে কেউ, সাইন ইন করা থাকুক বা না থাকুক",
  "doc.space.audience.granted": "শুধু যেসব প্রতিষ্ঠান, মানুষ ও প্ল্যানকে অনুমতি দেওয়া হয়েছে",
  "doc.space.audience.hint": "পাবলিক ও অনুমতিপ্রাপ্ত স্পেস শুধু প্ল্যাটফর্মের নিজস্ব ডকের জন্য।",
  "doc.space.theme": "যে থিমে খোলে",
  "doc.space.themeNone": "পাঠকের নিজের পছন্দ",
  "doc.space.create": "স্পেস তৈরি করুন",
  "doc.space.save": "স্পেস সংরক্ষণ করুন",
  "doc.space.saved": "স্পেস সংরক্ষিত হয়েছে।",
  "doc.space.delete": "স্পেস মুছুন",
  "doc.space.deleteConfirm": "{title} ও এর সব পাতা মুছুন",
  "doc.space.open": "পড়ুন",
  "doc.space.edit": "পাতা",

  "doc.tree.empty": "এখনও কোনো পাতা নেই। প্রথমটি যোগ করুন।",
  "doc.tree.add": "যোগ করুন",
  "doc.tree.addUnder": "{title}-এর নিচে যোগ করুন",
  "doc.tree.moveUp": "{title} উপরে সরান",
  "doc.tree.moveDown": "{title} নিচে সরান",
  "doc.tree.indent": "{title} উপরেরটির নিচে সরান",
  "doc.tree.outdent": "{title} এক স্তর বাইরে সরান",
  "doc.tree.delete": "{title} মুছুন",
  "doc.tree.deleteConfirm": "{title} ও এর নিচের সবকিছু মুছুন",
  "doc.page.kind": "ধরন",
  "doc.page.kind.page": "পাতা",
  "doc.page.kind.section": "বিভাগের শিরোনাম",
  "doc.page.kind.link": "বাইরের লিংক",
  "doc.page.status.draft": "খসড়া",
  "doc.page.status.published": "প্রকাশিত",
  "doc.page.status.changed": "অপ্রকাশিত পরিবর্তন",

  "doc.editor.title": "পাতা সম্পাদনা",
  "doc.editor.fields": "পাতার বিবরণ",
  "doc.page.title": "শিরোনাম",
  "doc.page.slug": "ঠিকানা",
  "doc.page.description": "বিবরণ",
  "doc.page.icon": "আইকন",
  "doc.page.url": "লিংকের ঠিকানা",
  "doc.page.markdown": "বিষয়বস্তু",
  "doc.page.markdownHint":
    'মার্কডাউন। `> [!NOTE]` একটি কলআউট তৈরি করে; ভেতরে `:::card{title="…" href="…"}` সহ `::::cards` একটি কার্ড গ্রিড তৈরি করে।',
  "doc.editor.write": "লিখুন",
  "doc.editor.preview": "প্রিভিউ",
  "doc.editor.previewEmpty": "প্রিভিউ করার মতো এখনও কিছু নেই।",
  "doc.editor.save": "খসড়া সংরক্ষণ করুন",
  "doc.editor.saving": "সংরক্ষণ করা হচ্ছে…",
  "doc.editor.saved": "খসড়া সংরক্ষিত হয়েছে।",
  "doc.editor.unsaved": "অসংরক্ষিত পরিবর্তন",
  "doc.editor.publish": "প্রকাশ করুন",
  "doc.editor.published": "সংস্করণ {revision} হিসেবে প্রকাশিত হয়েছে।",
  "doc.editor.structural": "বিভাগ ও লিংকের প্রকাশ করার মতো বিষয়বস্তু নেই: সংরক্ষণ করলেই সেগুলো দেখা যায়।",
  "doc.editor.view": "প্রকাশিত পাতা দেখুন",
  "doc.editor.image": "ছবি যোগ করুন",
  "doc.editor.imageUploading": "ছবি আপলোড হচ্ছে…",
  "doc.editor.imageTooLarge": "ছবি সর্বোচ্চ ৫ MB হতে পারে।",
  "doc.editor.imageType": "PNG, JPEG, WebP, GIF বা AVIF ছবি ব্যবহার করুন।",
  "doc.editor.back": "সব পাতা",

  "doc.grant.title": "কারা পড়তে পারবে",
  "doc.grant.description":
    "এই স্পেসটি একটি প্রতিষ্ঠান, একজন মানুষ, বা একটি প্ল্যানের সব প্রতিষ্ঠানের জন্য খুলে দিন।",
  "doc.grant.none": "প্ল্যাটফর্মের বাইরে এখনও কাউকে অনুমতি দেওয়া হয়নি।",
  "doc.grant.kind": "কাকে অনুমতি",
  "doc.grant.kind.organization": "একটি প্রতিষ্ঠান",
  "doc.grant.kind.user": "একজন মানুষ",
  "doc.grant.kind.plan": "একটি প্ল্যানের সবাই",
  "doc.grant.target": "কে",
  "doc.grant.target.organization": "প্রতিষ্ঠানের ঠিকানা বা আইডি",
  "doc.grant.target.user": "তাদের ইমেইল ঠিকানা",
  "doc.grant.target.plan": "প্ল্যানের কী",
  "doc.grant.reason": "কারণ",
  "doc.grant.reasonHint": "কেন দিচ্ছেন লিখুন, যাতে পরে যিনি দেখবেন তিনি বুঝতে পারেন এটি সরানো যায় কিনা।",
  "doc.grant.expires": "শেষ হবে",
  "doc.grant.expiresHint": "প্রত্যাহার না করা পর্যন্ত রাখতে খালি রাখুন।",
  "doc.grant.save": "অনুমতি দিন",
  "doc.grant.revoke": "প্রত্যাহার করুন",
  "doc.grant.expiresOn": "{date} পর্যন্ত",
  "doc.grant.expired": "মেয়াদ শেষ",
  "doc.grant.forever": "কোনো শেষ তারিখ নেই",

  "doc.revision.title": "ইতিহাস",
  "doc.revision.none": "এখনও প্রকাশিত হয়নি।",
  "doc.revision.item": "সংস্করণ {revision}",
  "doc.revision.restore": "খসড়ায় ফিরিয়ে আনুন",
  "doc.revision.restored": "সংস্করণ {revision} এখন খসড়া। প্রকাশ করলে এটি চালু হবে।",
};
