export const notification = {
  "notification.kind.member.joined.title": "কেউ যোগ দিয়েছেন",
  "notification.kind.member.joined.body": "এই প্রতিষ্ঠানে একজন নতুন সদস্য যোগ দিয়েছেন।",
  "notification.kind.member.role.changed.title": "আপনার ভূমিকা বদলেছে",
  "notification.kind.member.role.changed.body":
    "একজন প্রশাসক এখানে আপনি কী করতে পারেন তা বদলেছেন। আপনার নতুন ভূমিকা দেখতে সদস্য পাতাটি খুলুন।",

  "notification.archived.title": "এক বছরের বেশি পুরনো",
  "notification.archived.description": "সরাসরি কোল্ড স্টোরেজ থেকে পড়া হয়। পুনরুদ্ধারের অপেক্ষা নেই।",
  "notification.archived.month": "মাস",
  "notification.archived.column.kind": "কী ঘটেছে",
  "notification.archived.column.created": "কখন",
  "notification.archived.noMonths": "আপনার কিছুই এখনো আর্কাইভ হয়নি।",
  "notification.archived.empty": "এই মাসে আপনার কিছু নেই।",
  "notification.archived.more": "আরও দেখুন",
  "notification.inbox.title": "বিজ্ঞপ্তি",
  "notification.inbox.empty": "এখনও কিছু নেই। হালনাগাদগুলো এখানে দেখা যাবে।",
  "notification.inbox.emptyUnread": "অপঠিত কিছু নেই। এখানকার সবকিছু দেখা হয়ে গেছে।",
  "notification.inbox.error": "আপনার বিজ্ঞপ্তিগুলো লোড করা যায়নি।",
  "notification.inbox.loadMore": "পুরনোগুলো দেখুন",
  "notification.inbox.markAllRead": "সবগুলো পঠিত হিসেবে চিহ্নিত করুন",
  "notification.inbox.unreadOnly": "শুধু অপঠিত",
  "notification.inbox.markRead": "পঠিত চিহ্নিত করুন",
  "notification.inbox.unreadCount": "{count}টি অপঠিত",
  "notification.inbox.open": "বিজ্ঞপ্তি খুলুন",
  "notification.peek.loading": "লোড হচ্ছে…",
  "notification.peek.markRead": "পঠিত চিহ্নিত করুন",
  "notification.peek.seeAll": "সব বিজ্ঞপ্তি দেখুন",

  "notification.preference.title": "আপনি কীভাবে খবর পাবেন",
  "notification.preference.description":
    "প্রতিটি ধরনের হালনাগাদ আপনার কাছে কীভাবে পৌঁছাবে তা বেছে নিন। অ্যাপের বিজ্ঞপ্তি সবসময় এই তালিকায় থাকবে; এই সেটিংস ঠিক করে আপনাকে বাধা দেওয়া হবে কি না এবং আমরা ইমেল পাঠাব কি না।",
  "notification.preference.category.membership": "সদস্য ও ভূমিকা",
  "notification.preference.channel.in_app": "অ্যাপে",
  "notification.preference.channel.email": "ইমেলে",
  "notification.preference.mode.immediate": "সঙ্গে সঙ্গে",
  "notification.preference.mode.digest": "দিনে একবার",
  "notification.preference.mode.off": "বন্ধ",
  "notification.preference.saved": "সংরক্ষণ করা হয়েছে।",
} as const;
