export const platform = {
  "platform.title": "প্ল্যাটফর্ম",
  "platform.nav.label": "প্ল্যাটফর্ম",
  "platform.nav.status": "অবস্থা",
  "platform.nav.accounts": "অ্যাকাউন্ট",
  "platform.nav.entitlements": "প্ল্যান ও অধিকার",
  "platform.nav.flags": "ফিচার ফ্ল্যাগ",
  "platform.nav.team": "টিম",
  "platform.nav.roles": "ভূমিকা",
  "platform.nav.docs": "ডক",
  "platform.nav.open": "প্ল্যাটফর্ম প্রতিষ্ঠান খুলুন",
  "platform.subtitle":
    "যে সেটিংস কোনও একক টেন্যান্টের ঊর্ধ্বে। প্ল্যাটফর্ম প্রতিষ্ঠানে ভূমিকার মাধ্যমে পাওয়া যায়, আপনি যে টেন্যান্টে সাইন ইন করেছেন তার মাধ্যমে নয়।",
  "platform.status.title": "অবস্থা",
  "platform.organization": "প্ল্যাটফর্ম প্রতিষ্ঠান",
  "platform.organization.detail": "{name} ({slug})",
  "platform.health.title": "নির্ভরতা",
  "platform.health.healthy": "সুস্থ",
  "platform.health.degraded": "অবনত",
  "platform.health.database": "পোস্টগ্রেস",
  "platform.health.cache": "রেডিস — ক্যাশ",
  "platform.health.queue": "রেডিস — সারি",
  "platform.health.analytics": "ক্লিকহাউস",
  "platform.health.realtime": "রিয়েলটাইম ফ্যান-আউট",
  "platform.health.replica": "পোস্টগ্রেস — রেপ্লিকা",
  "platform.replica.lag": "রেপ্লিকার বিলম্ব: {seconds} সেকেন্ড",
  "platform.replica.title": "রেপ্লিকা থেকে পড়া",
  "platform.replica.on": "চালু",
  "platform.replica.off": "বন্ধ",
  "platform.replica.enable": "ব্যাচ পড়া রেপ্লিকায় পাঠান",
  "platform.replica.disable": "শুধু প্রাইমারি থেকে পড়ুন",
  "platform.replica.detail":
    "চালু থাকলে ওয়ার্কারের ব্যাচ পড়া — অ্যানালিটিক্স প্রজেকশন ও তার রাত্রিকালীন মিলান — রেপ্লিকা ব্যবহার করে। রেপ্লিকা প্রাইমারির সমান হলে তবেই একটি পড়া তা ব্যবহার করে, নইলে প্রাইমারি থেকে পড়ে।",
  "platform.state.up": "চালু",
  "platform.state.down": "বন্ধ",
  "platform.state.absent": "কনফিগার করা নেই",

  // The organization field on the export and delete panels. Named for the storage page
  // they came from, which lite does not have.
  "platform.storage.filter": "প্রতিষ্ঠানের আইডি",
  "platform.tenantExport.title": "একটি টেন্যান্ট রপ্তানি",
  "platform.tenantExport.description":
    "টেন্যান্টের প্রতিটি টেবিলের জন্য একটি করে অবজেক্ট, সঙ্গে ক্যাটালগ সারি এবং গণনা ও চেকসামের একটি ম্যানিফেস্ট। এপিআই কী ও আমন্ত্রণের হ্যাশ বাদ দেওয়া হয়।",
  "platform.tenantExport.action": "রপ্তানি শুরু",
  "platform.tenantExport.queued": "{jobId} হিসেবে সারিবদ্ধ। ওয়ার্কার শেষ করলে অবজেক্টগুলি নিচে দেখা যাবে।",
  "platform.tenantExport.empty": "এই টেন্যান্টের কোনো রপ্তানি অবজেক্ট নেই।",
  "platform.tenantExport.expiry": "ডাউনলোড লিঙ্ক পনেরো মিনিটে শেষ হয়; অবজেক্টগুলি সাত দিন পর মুছে যায়।",
  "platform.tenantDelete.title": "একটি টেন্যান্ট মুছুন",
  "platform.tenantDelete.warning":
    "প্রতিটি মাস আগে কোল্ড স্টোরেজে আর্কাইভ হয়, তারপর টেন্যান্টের পার্টিশন ও ক্যাটালগ সারি সরানো হয়। আর্কাইভ করা অবজেক্ট ত্রিশ দিন পর মুছে যায়।",
  "platform.tenantDelete.slug": "নিশ্চিত করতে স্লাগ লিখুন",
  "platform.tenantDelete.slug.hint": "সার্ভারও এটি মিলিয়ে দেখে।",
  "platform.tenantDelete.action": "টেন্যান্ট মুছুন",
  "platform.tenantDelete.queued": "{jobId} হিসেবে কিউতে। পার্টিশন বাদ দেওয়ার আগে প্রতিটি মাস আর্কাইভ হয়।",

  "platform.flags.title": "ফিচার ফ্ল্যাগ",
  "platform.flags.description":
    "প্রতিটি ফ্ল্যাগ কোডে একজন মালিক ও মেয়াদ শেষের তারিখসহ ঘোষিত, আর এখানে চালু বা বন্ধ করা হয় — সবার জন্য, অথবা শুধু নিচে তালিকাভুক্ত প্রতিষ্ঠানগুলোর জন্য।",
  "platform.flags.empty": "কোনো ফ্ল্যাগ ঘোষিত নেই, সংরক্ষিতও নেই।",
  "platform.flags.column.flag": "ফ্ল্যাগ",
  "platform.flags.column.owner": "মালিক",
  "platform.flags.column.expires": "মেয়াদ শেষ",
  "platform.flags.column.everyone": "সবার জন্য",
  "platform.flags.column.organizations": "এছাড়াও চালু",
  "platform.flags.on": "চালু",
  "platform.flags.off": "বন্ধ",
  "platform.flags.enable": "সবার জন্য চালু করুন",
  "platform.flags.disable": "সবার জন্য বন্ধ করুন",
  "platform.flags.expired": "মেয়াদ পেরিয়ে গেছে — এটি সরিয়ে ফেলুন",
  "platform.flags.orphaned": "কোডে ঘোষিত নেই",
  "platform.flags.orphaned.detail":
    "কোড আর এই ফ্ল্যাগ ঘোষণা করে না, তাই কিছুই এটি পড়ে না। মুছে ফেলতে এটি বন্ধ করুন।",
  "platform.flags.organizations.none": "কোনোটি নয়",
  "platform.flags.organization.label": "প্রতিষ্ঠানের আইডি বা স্লাগ",
  "platform.flags.organization.add": "এই প্রতিষ্ঠানের জন্য চালু করুন",
  "platform.flags.organization.remove": "{slug}-এর জন্য বন্ধ করুন",

  "platform.entitlements.title": "প্ল্যান ও প্রাপ্য অনুমতি",
  "platform.entitlements.description":
    "প্ল্যান হলো একটি প্রতিষ্ঠান যে অনুমতিগুলোর জন্য অর্থ দিয়েছে। ছোট প্ল্যানে সরালে বাকিগুলো তার ভূমিকা থেকে লুকানো হয়, মোছা হয় না, তাই ফিরিয়ে আনলে সেগুলো ফিরে আসে।",
  "platform.plans.title": "প্ল্যান",
  "platform.plans.column.plan": "প্ল্যান",
  "platform.plans.column.permissions": "অনুমতি",
  "platform.plans.column.organizations": "প্রতিষ্ঠান",
  "platform.plans.every": "সব অনুমতি",
  "platform.plans.default": "নতুন সাইনআপ",
  "platform.plans.system": "অন্তর্নির্মিত",
  "platform.plans.makeDefault": "নতুন সাইনআপের জন্য ব্যবহার করুন",
  "platform.plans.edit": "সম্পাদনা",
  "platform.plans.delete": "মুছুন",
  "platform.plans.new": "নতুন প্ল্যান",
  "platform.plan.key": "কী",
  "platform.plan.name": "নাম",
  "platform.plan.description": "বিবরণ",
  "platform.plan.module": "{module}-এর সবকিছু",
  "platform.plan.closure":
    "একটি অনুমতি বাছলে তার প্রয়োজনীয়গুলোও বাছাই হয়, আর বাদ দিলে তার উপর নির্ভরশীলগুলোও বাদ যায়।",
  "platform.plan.save": "প্ল্যান সংরক্ষণ করুন",
  "platform.plan.cancel": "বাতিল",
  "platform.entitlement.title": "একটি প্রতিষ্ঠান",
  "platform.entitlement.lookup": "প্রতিষ্ঠানের আইডি বা স্লাগ",
  "platform.entitlement.plan": "প্ল্যান",
  "platform.entitlement.assign": "এই প্ল্যানে সরান",
  "platform.entitlement.summary": "{count}টি অনুমতির অধিকারী।",
  "platform.entitlement.role": "{role} তার তালিকার {listed}টির মধ্যে {entitled}টি পায়।",
  "platform.entitlement.adjustments": "সমন্বয়",
  "platform.entitlement.adjustments.none": "কোনোটি নয় — প্ল্যানই সব ঠিক করে।",
  "platform.entitlement.column.permission": "অনুমতি",
  "platform.entitlement.column.effect": "প্রভাব",
  "platform.entitlement.column.reason": "কারণ",
  "platform.entitlement.column.expires": "মেয়াদ শেষ",
  "platform.entitlement.never": "কখনো না",
  "platform.entitlement.effect.add": "যোগ করা",
  "platform.entitlement.effect.remove": "সরানো",
  "platform.entitlement.clear": "মুছুন",
  "platform.entitlement.adjust": "সমন্বয় করুন",
  "platform.entitlement.adjust.effect": "প্রভাব",
  "platform.entitlement.adjust.reason": "কারণ",
  "platform.entitlement.adjust.expires": "মেয়াদ শেষ (স্থায়ী করতে খালি রাখুন)",
  "platform.entitlement.adjusted": "সমন্বয় হয়েছে: {permissions}",
  "platform.modules.title": "মডিউল সুইচ",
  "platform.modules.description":
    "ঘটনার সময়ের জন্য। বন্ধ করা মডিউল প্রতিটি প্রতিষ্ঠানের জন্য বন্ধ থাকে, প্ল্যান যা-ই হোক, যতক্ষণ না আবার চালু করা হয়।",
  "platform.modules.on": "চালু",
  "platform.modules.off": "বন্ধ",
  "platform.modules.disable": "বন্ধ করুন",
  "platform.modules.enable": "আবার চালু করুন",
  "platform.modules.reason": "কারণ",

  // ── accounts (`AX6.8`) ──
  "platform.accounts.title": "অ্যাকাউন্ট",
  "platform.accounts.description":
    "ঠিকানা দিয়ে একটি অ্যাকাউন্ট খুঁজুন, এটি যে সব প্রতিষ্ঠানের সদস্য তা দেখুন, এবং অ্যাকাউন্টটি ঝুঁকিতে পড়লে একবারে সব জায়গায় আটকে দিন।",
  "platform.account.lookup": "ইমেইল ঠিকানা",
  "platform.account.active": "সক্রিয়",
  "platform.account.suspendedOn": "{date} থেকে স্থগিত",
  "platform.account.memberships": "প্রতিষ্ঠান",
  "platform.account.memberships.none": "এই অ্যাকাউন্টটি কোনো প্রতিষ্ঠানের সদস্য নয়।",
  "platform.account.column.organization": "প্রতিষ্ঠান",
  "platform.account.column.role": "ভূমিকা",
  "platform.account.column.permission": "অনুমতি",
  "platform.account.column.reason": "কারণ",
  "platform.account.deactivated": "প্রতিষ্ঠান দ্বারা নিষ্ক্রিয়",
  "platform.account.reason": "কারণ (এটি যে সব প্রতিষ্ঠানের সদস্য, তারা সবাই পড়তে পারবে)",
  "platform.account.suspend": "সব জায়গায় স্থগিত করুন",
  "platform.account.reinstate": "পুনর্বহাল করুন",
  "platform.account.denies": "প্ল্যাটফর্ম দ্বারা প্রত্যাখ্যাত",
  "platform.account.denies.none": "প্ল্যাটফর্ম কিছুই প্রত্যাখ্যান করেনি।",
  "platform.account.clear": "মুছুন",
  "platform.account.deny": "প্রত্যাখ্যান করুন",
  "platform.account.deny.organization": "প্রতিষ্ঠানে",
  "platform.account.denied": "প্রত্যাখ্যাত: {permissions}",
} as const;
