export const platform = {
  "platform.title": "প্ল্যাটফর্ম",
  "platform.subtitle":
    "যে সেটিংস কোনও একক টেন্যান্টের ঊর্ধ্বে। প্ল্যাটফর্ম প্রতিষ্ঠানে ভূমিকার মাধ্যমে পাওয়া যায়, আপনি যে টেন্যান্টে সাইন ইন করেছেন তার মাধ্যমে নয়।",
  "platform.status.title": "অবস্থা",
  "platform.organization": "প্ল্যাটফর্ম প্রতিষ্ঠান",
  "platform.organization.detail": "{name} ({slug})",
  "platform.health.title": "নির্ভরতা",
  "platform.health.healthy": "সুস্থ",
  "platform.health.degraded": "অবনত",
  "platform.health.database": "পোস্টগ্রেস",
  "platform.health.cache": "রেডিস — ক্যাশ",
  "platform.health.queue": "রেডিস — সারি",
  "platform.health.analytics": "ক্লিকহাউস",
  "platform.health.realtime": "রিয়েলটাইম ফ্যান-আউট",
  "platform.health.replica": "পোস্টগ্রেস — রেপ্লিকা",
  "platform.replica.lag": "রেপ্লিকার বিলম্ব: {seconds} সেকেন্ড",
  "platform.replica.title": "রেপ্লিকা থেকে পড়া",
  "platform.replica.on": "চালু",
  "platform.replica.off": "বন্ধ",
  "platform.replica.enable": "ব্যাচ পড়া রেপ্লিকায় পাঠান",
  "platform.replica.disable": "শুধু প্রাইমারি থেকে পড়ুন",
  "platform.replica.detail":
    "চালু থাকলে ওয়ার্কারের ব্যাচ পড়া — অ্যানালিটিক্স প্রজেকশন ও তার রাত্রিকালীন মিলান — রেপ্লিকা ব্যবহার করে। রেপ্লিকা প্রাইমারির সমান হলে তবেই একটি পড়া তা ব্যবহার করে, নইলে প্রাইমারি থেকে পড়ে।",
  "platform.state.up": "চালু",
  "platform.state.down": "বন্ধ",
  "platform.state.absent": "কনফিগার করা নেই",

  "platform.retention.title": "সংরক্ষণকাল",
  "platform.retention.description":
    "প্রতিটি টেবিল পোস্টগ্রেসে কত দিন তথ্য রাখে, এবং তার পরে সংরক্ষিত মাসগুলি অবজেক্ট স্টোরেজে কত দিন থাকে। এখানে সারি না থাকলে বিল্ট-ইন ডিফল্ট প্রযোজ্য।",
  "platform.retention.table": "টেবিল",
  "platform.retention.hotMonths": "পোস্টগ্রেসে মাস",
  "platform.retention.coldMonths": "কোল্ড স্টোরেজে মাস",
  "platform.retention.coldMonths.hint": "ফাঁকা রাখলে কখনও মেয়াদ শেষ হয় না।",
  "platform.retention.mode": "মাস পুরোনো হলে",
  "platform.retention.mode.archive": "সংরক্ষণ করে তারপর বাদ",
  "platform.retention.mode.drop": "বাদ",
  "platform.retention.save": "সংরক্ষণ",
  "platform.retention.default": "ডিফল্ট",
  "platform.retention.mode.warning": "এভাবে বাদ দেওয়া মাস কোল্ড স্টোরেজে থাকে না এবং ফিরিয়ে আনা যায় না।",
  "platform.retention.neverDropped": "কখনও বাদ দেওয়া হয় না — ডোমেইন তথ্য।",
  "platform.retention.clickhouse": "ক্লিকহাউস",
  "platform.retention.clickhouse.months": "বিশ্লেষণ ইতিহাসের মাস",
  "platform.retention.preview.loading": "এটি কী বাদ দেবে তা হিসাব করা হচ্ছে…",
  "platform.retention.preview.invalid": "অন্তত এক, পূর্ণসংখ্যায় মাস লিখুন।",
  "platform.retention.preview.failed": "এটি কী বাদ দেবে তা হিসাব করা যায়নি।",
  "platform.retention.preview.none": "পরবর্তী চালনায় কিছুই বাদ যাবে না।",
  "platform.retention.preview.summary":
    "পরবর্তী চালনা {partitions}টি পার্টিশন, আনুমানিক {rows}টি সারি, {bytes} বাইট বাদ দেবে।",
  "platform.tenantRetention.title": "একটি টেন্যান্টের সংরক্ষণকাল",
  "platform.tenantRetention.description":
    "একটি প্রতিষ্ঠানের জন্য টেবিলের নিজস্ব সংখ্যা অগ্রাহ্য করে। ক্যালেন্ডার ইতিমধ্যেই যে টেবিলগুলি অবসর দেয়, কেবল সেগুলিই অগ্রাহ্য করা যায়।",
  "platform.tenantRetention.organization": "প্রতিষ্ঠানের আইডি",
  "platform.tenantRetention.organizationFirst": "এটি কী সরাবে তা দেখতে একটি প্রতিষ্ঠান আইডি লিখুন।",
  "platform.tenantRetention.coldNote": "টেবিলের চেয়ে কম কোল্ড মাস বাকেট নয়, রাতের কাজ কার্যকর করে।",
  "platform.tenantRetention.saved": "সংরক্ষিত।",
  "platform.tenantExport.title": "একটি টেন্যান্ট রপ্তানি",
  "platform.tenantExport.description":
    "টেন্যান্টের প্রতিটি টেবিলের জন্য একটি করে অবজেক্ট, সঙ্গে ক্যাটালগ সারি এবং গণনা ও চেকসামের একটি ম্যানিফেস্ট। এপিআই কী ও আমন্ত্রণের হ্যাশ বাদ দেওয়া হয়।",
  "platform.tenantExport.action": "রপ্তানি শুরু",
  "platform.tenantExport.queued": "{jobId} হিসেবে সারিবদ্ধ। ওয়ার্কার শেষ করলে অবজেক্টগুলি নিচে দেখা যাবে।",
  "platform.tenantExport.empty": "এই টেন্যান্টের কোনো রপ্তানি অবজেক্ট নেই।",
  "platform.tenantExport.expiry": "ডাউনলোড লিঙ্ক পনেরো মিনিটে শেষ হয়; অবজেক্টগুলি সাত দিন পর মুছে যায়।",
  "platform.tenantDelete.title": "একটি টেন্যান্ট মুছুন",
  "platform.tenantDelete.warning":
    "প্রতিটি মাস আগে কোল্ড স্টোরেজে আর্কাইভ হয়, তারপর টেন্যান্টের পার্টিশন ও ক্যাটালগ সারি সরানো হয়। আর্কাইভ করা অবজেক্ট ত্রিশ দিন পর মুছে যায়।",
  "platform.tenantDelete.slug": "নিশ্চিত করতে স্লাগ লিখুন",
  "platform.tenantDelete.slug.hint": "সার্ভারও এটি মিলিয়ে দেখে।",
  "platform.tenantDelete.action": "টেন্যান্ট মুছুন",
  "platform.tenantDelete.queued": "{jobId} হিসেবে কিউতে। পার্টিশন বাদ দেওয়ার আগে প্রতিটি মাস আর্কাইভ হয়।",
  "platform.gaps.title": "ফাঁক",
  "platform.gaps.none": "প্রতিটি আর্কাইভ করা মাস অ্যানালিটিক্স স্টোরে পৌঁছেছে।",
  "platform.gaps.row": "{period} — {tenants}টি আর্কাইভ অবজেক্ট কখনো প্রজেক্ট হয়নি।",
  "platform.gaps.reproject": "এই মাস পুনরায় প্রজেক্ট করুন",
  "platform.gaps.reason": "কেন ফাঁক আছে তা লগ লাইনে থাকে, সারিতে নয়। পুনরায় প্রজেক্ট করা ইডেমপোটেন্ট।",
  "platform.gaps.queued": "{jobId} হিসেবে সারিবদ্ধ; {objects}টি অবজেক্ট পড়তে হবে।",
  "platform.switch.title": "প্রজেকশন",
  "platform.switch.on": "চালু",
  "platform.switch.off": "বিরতি",
  "platform.switch.pause": "প্রজেকশন থামান",
  "platform.switch.resume": "প্রজেকশন চালু করুন",
  "platform.switch.notConfigured": "কনফিগার করা নেই",
  "platform.switch.notConfigured.detail":
    "এই ডিপ্লয়মেন্টে কোনো অ্যানালিটিক্স স্টোর নেই। চালু করতে CLICKHOUSE_URL সেট করুন।",
  "platform.switch.deadline":
    "বিরতির সময় সারিগুলি প্রজেক্ট হয় না। অডিট টেবিল {months} মাস রাখে; তার মধ্যে চালু করুন, নয়তো কোল্ড স্টোরেজ থেকে ফাঁক পূরণ করুন।",
  "platform.switch.deadline.unbounded":
    "বিরতির সময় সারিগুলি প্রজেক্ট হয় না। অডিট টেবিলের কোনো সীমা নেই, তাই ফাঁক পুনরায় চালানো যাবে।",
  "platform.projection.title": "অ্যানালিটিক্স প্রজেকশন",
  "platform.projection.description":
    "কোন কাজগুলি অ্যানালিটিক্স স্টোরে পৌঁছায়, এবং কতদিন। ফাঁকা রাখলে ডিফল্ট {months} মাস।",
  "platform.projection.loading": "লোড হচ্ছে…",
  "platform.projection.notConfigured":
    "কোনো অ্যানালিটিক্স স্টোর কনফিগার করা নেই। সারিগুলি সংরক্ষিত হয় এবং স্টোর চালু হলে কার্যকর হয়।",
  "platform.projection.drifted": "স্টোরে এই সারিগুলির চেয়ে ভিন্ন এক্সপ্রেশন আছে। রাতের কাজ সেটি ঠিক করে।",
  "platform.projection.saveTtl": "মাস সংরক্ষণ",
  "platform.projection.stop": "প্রজেকশন বন্ধ",
  "platform.projection.resume": "প্রজেকশন চালু",
  "platform.projection.excluded.warning":
    "স্টোরে থাকা সারিগুলি থেকে যায়; নতুন সারি আর আসে না। অডিট টেবিলের সংরক্ষণকাল পার হলে এই ফাঁক কেবল কোল্ড স্টোরেজ থেকে পূরণ করা যায়।",
  "platform.storage.title": "টেন্যান্ট অনুযায়ী কোল্ড স্টোরেজ",
  "platform.storage.description":
    "শুধু আর্কাইভ করা মাস। হট পোস্টগ্রেস আকার কোনো টেন্যান্টের নামে লেখা যায় না; টেবিলভিত্তিক হট আকার সংরক্ষণকাল স্ক্রিনে আছে।",
  "platform.storage.filter": "প্রতিষ্ঠানের আইডি",
  "platform.storage.empty": "এখনো কিছু আর্কাইভ হয়নি।",
  "platform.storage.column.organization": "প্রতিষ্ঠান",
  "platform.storage.column.table": "টেবিল",
  "platform.storage.column.bytes": "আকার",
  "platform.storage.column.rows": "সারি",
  "platform.storage.column.months": "মাস",
  "platform.storage.column.period": "মাস",
  "platform.storage.column.actionCounts": "কাজ",
  "platform.storage.column.projected": "প্রজেক্ট হয়েছে",
  "platform.storage.notProjected": "কখনো নয়",
  "platform.storage.months.title": "আর্কাইভ করা মাসগুলি",
  "platform.restore.title": "একটি মাস ফিরিয়ে আনুন",
  "platform.restore.description":
    "কোল্ড স্টোরেজ থেকে একটি মাস পড়ে আনে। টেবিলের হট উইন্ডোর ভিতরে হলে এটি সংযুক্ত হয়ে আবার সক্রিয় হয়; বাইরে হলে একটি স্ক্র্যাচ টেবিলে থাকে — সক্রিয় করতে হলে আগে হট মাস বাড়ান।",
  "platform.restore.table": "টেবিল",
  "platform.restore.period": "মাস",
  "platform.restore.submit": "ফিরিয়ে আনুন",
  "platform.restore.queued": "{jobId} হিসেবে সারিবদ্ধ। {objects}টি অবজেক্ট পড়া হবে।",
  "platform.retention.drift": "স্টোরে অন্য কিছু আছে। রাতের কাজ এটি ঠিক করবে; এখন সেখানে আছে {actual}।",
  "platform.shards.title": "শার্ড ম্যাপ",
  "platform.shards.description":
    "প্রতি ফিজিক্যাল নোডে একটি সারি, ডিরেক্টরি থেকে গোনা। একটি টেন্যান্ট তৈরির সময় একবারই বসানো হয়, আর নোড বদলায় শুধু তখনই যখন একটি মুভ জব তাকে অন্যত্র সরায়।",
  "platform.shards.empty": "ডিরেক্টরি ফাঁকা — এখনও কোনো টেন্যান্ট তৈরি হয়নি।",
  "platform.shards.column.node": "নোড",
  "platform.shards.column.tenants": "টেন্যান্ট",
  "platform.shards.column.lastAssigned": "সর্বশেষ বসানো",
  "platform.shards.column.lastMoved": "সর্বশেষ সরানো",
  "platform.shards.never": "কখনও নয়",
  "platform.shards.expand": "টেন্যান্ট দেখান",
  "platform.shards.collapse": "টেন্যান্ট লুকান",
  "platform.shards.tenants.title": "নোড {node}-এর টেন্যান্ট",
  "platform.shards.tenants.empty": "এই নোডে কোনো টেন্যান্ট নেই।",
  "platform.shards.column.organization": "প্রতিষ্ঠান",
  "platform.shards.column.assigned": "বসানো",
  "platform.shards.column.overrides": "রিটেনশন",
  "platform.shards.column.actions": "কাজ",
  "platform.shards.overrides.default": "ডিফল্ট",
  "platform.shards.overrides.count": "{count}টি বদলানো",
  "platform.shards.move": "সরান",
  "platform.shards.move.unavailable":
    "টেন্যান্ট সরাতে দ্বিতীয় একটি ডেটাবেস নোড লাগে — একটি নোডে সরানোর কোনো জায়গা নেই।",
  "platform.shards.move.title": "{name} সরান",
  "platform.shards.move.warning":
    "{name} নোড {node}-এ আছে। সব সারি কপি না হওয়া পর্যন্ত এর লেখা প্রত্যাখ্যাত হবে, আর পুরনো কপিটি গ্রেস পিরিয়ড পর্যন্ত রাখা হবে যাতে সরানোটা ফিরিয়ে নেওয়া যায়।",
  "platform.shards.move.to": "নোড {node}-এ সরান",
  "platform.shards.move.cancel": "বাতিল",
  "platform.shards.move.queued":
    "{jobId} হিসেবে সারিতে রাখা হয়েছে। ওয়ার্কার সব সারি কপি করার পর টেন্যান্টটি নতুন নোডে দেখা যাবে।",
  "platform.shards.manage": "স্টোরেজ ও মুছে ফেলা",
  "platform.shards.page": "{total}-এর মধ্যে {from}–{to}",
  "platform.shards.page.previous": "আগের",
  "platform.shards.page.next": "পরের",
  "platform.shards.lookup.title": "টেন্যান্ট খুঁজুন",
  "platform.shards.lookup.label": "প্রতিষ্ঠানের আইডি বা স্লাগ",
  "platform.shards.lookup.empty": "এমন কোনো টেন্যান্ট নেই।",
  "platform.shards.lookup.found": "{name} ({slug}) আছে নোড {node}-এ।",

  "platform.flags.title": "ফিচার ফ্ল্যাগ",
  "platform.flags.description":
    "প্রতিটি ফ্ল্যাগ কোডে একজন মালিক ও মেয়াদ শেষের তারিখসহ ঘোষিত, আর এখানে চালু বা বন্ধ করা হয় — সবার জন্য, অথবা শুধু নিচে তালিকাভুক্ত প্রতিষ্ঠানগুলোর জন্য।",
  "platform.flags.empty": "কোনো ফ্ল্যাগ ঘোষিত নেই, সংরক্ষিতও নেই।",
  "platform.flags.column.flag": "ফ্ল্যাগ",
  "platform.flags.column.owner": "মালিক",
  "platform.flags.column.expires": "মেয়াদ শেষ",
  "platform.flags.column.everyone": "সবার জন্য",
  "platform.flags.column.organizations": "এছাড়াও চালু",
  "platform.flags.on": "চালু",
  "platform.flags.off": "বন্ধ",
  "platform.flags.enable": "সবার জন্য চালু করুন",
  "platform.flags.disable": "সবার জন্য বন্ধ করুন",
  "platform.flags.expired": "মেয়াদ পেরিয়ে গেছে — এটি সরিয়ে ফেলুন",
  "platform.flags.orphaned": "কোডে ঘোষিত নেই",
  "platform.flags.orphaned.detail":
    "কোড আর এই ফ্ল্যাগ ঘোষণা করে না, তাই কিছুই এটি পড়ে না। মুছে ফেলতে এটি বন্ধ করুন।",
  "platform.flags.organizations.none": "কোনোটি নয়",
  "platform.flags.organization.label": "প্রতিষ্ঠানের আইডি বা স্লাগ",
  "platform.flags.organization.add": "এই প্রতিষ্ঠানের জন্য চালু করুন",
  "platform.flags.organization.remove": "{slug}-এর জন্য বন্ধ করুন",

  "platform.entitlements.title": "প্ল্যান ও প্রাপ্য অনুমতি",
  "platform.entitlements.description":
    "প্ল্যান হলো একটি প্রতিষ্ঠান যে অনুমতিগুলোর জন্য অর্থ দিয়েছে। ছোট প্ল্যানে সরালে বাকিগুলো তার ভূমিকা থেকে লুকানো হয়, মোছা হয় না, তাই ফিরিয়ে আনলে সেগুলো ফিরে আসে।",
  "platform.plans.title": "প্ল্যান",
  "platform.plans.column.plan": "প্ল্যান",
  "platform.plans.column.permissions": "অনুমতি",
  "platform.plans.column.organizations": "প্রতিষ্ঠান",
  "platform.plans.every": "সব অনুমতি",
  "platform.plans.default": "নতুন সাইনআপ",
  "platform.plans.system": "অন্তর্নির্মিত",
  "platform.plans.makeDefault": "নতুন সাইনআপের জন্য ব্যবহার করুন",
  "platform.plans.edit": "সম্পাদনা",
  "platform.plans.delete": "মুছুন",
  "platform.plans.new": "নতুন প্ল্যান",
  "platform.plan.key": "কী",
  "platform.plan.name": "নাম",
  "platform.plan.description": "বিবরণ",
  "platform.plan.module": "{module}-এর সবকিছু",
  "platform.plan.closure":
    "একটি অনুমতি বাছলে তার প্রয়োজনীয়গুলোও বাছাই হয়, আর বাদ দিলে তার উপর নির্ভরশীলগুলোও বাদ যায়।",
  "platform.plan.save": "প্ল্যান সংরক্ষণ করুন",
  "platform.plan.cancel": "বাতিল",
  "platform.entitlement.title": "একটি প্রতিষ্ঠান",
  "platform.entitlement.lookup": "প্রতিষ্ঠানের আইডি বা স্লাগ",
  "platform.entitlement.plan": "প্ল্যান",
  "platform.entitlement.assign": "এই প্ল্যানে সরান",
  "platform.entitlement.summary": "{count}টি অনুমতির অধিকারী।",
  "platform.entitlement.role": "{role} তার তালিকার {listed}টির মধ্যে {entitled}টি পায়।",
  "platform.entitlement.adjustments": "সমন্বয়",
  "platform.entitlement.adjustments.none": "কোনোটি নয় — প্ল্যানই সব ঠিক করে।",
  "platform.entitlement.column.permission": "অনুমতি",
  "platform.entitlement.column.effect": "প্রভাব",
  "platform.entitlement.column.reason": "কারণ",
  "platform.entitlement.column.expires": "মেয়াদ শেষ",
  "platform.entitlement.never": "কখনো না",
  "platform.entitlement.effect.add": "যোগ করা",
  "platform.entitlement.effect.remove": "সরানো",
  "platform.entitlement.clear": "মুছুন",
  "platform.entitlement.adjust": "সমন্বয় করুন",
  "platform.entitlement.adjust.effect": "প্রভাব",
  "platform.entitlement.adjust.reason": "কারণ",
  "platform.entitlement.adjust.expires": "মেয়াদ শেষ (স্থায়ী করতে খালি রাখুন)",
  "platform.entitlement.adjusted": "সমন্বয় হয়েছে: {permissions}",
  "platform.modules.title": "মডিউল সুইচ",
  "platform.modules.description":
    "ঘটনার সময়ের জন্য। বন্ধ করা মডিউল প্রতিটি প্রতিষ্ঠানের জন্য বন্ধ থাকে, প্ল্যান যা-ই হোক, যতক্ষণ না আবার চালু করা হয়।",
  "platform.modules.on": "চালু",
  "platform.modules.off": "বন্ধ",
  "platform.modules.disable": "বন্ধ করুন",
  "platform.modules.enable": "আবার চালু করুন",
  "platform.modules.reason": "কারণ",

  // ── accounts (`AX6.8`) ──
  "platform.accounts.title": "অ্যাকাউন্ট",
  "platform.accounts.description":
    "ঠিকানা দিয়ে একটি অ্যাকাউন্ট খুঁজুন, এটি যে সব প্রতিষ্ঠানের সদস্য তা দেখুন, এবং অ্যাকাউন্টটি ঝুঁকিতে পড়লে একবারে সব জায়গায় আটকে দিন।",
  "platform.account.lookup": "ইমেইল ঠিকানা",
  "platform.account.active": "সক্রিয়",
  "platform.account.suspendedOn": "{date} থেকে স্থগিত",
  "platform.account.memberships": "প্রতিষ্ঠান",
  "platform.account.memberships.none": "এই অ্যাকাউন্টটি কোনো প্রতিষ্ঠানের সদস্য নয়।",
  "platform.account.column.organization": "প্রতিষ্ঠান",
  "platform.account.column.role": "ভূমিকা",
  "platform.account.column.permission": "অনুমতি",
  "platform.account.column.reason": "কারণ",
  "platform.account.deactivated": "প্রতিষ্ঠান দ্বারা নিষ্ক্রিয়",
  "platform.account.reason": "কারণ (এটি যে সব প্রতিষ্ঠানের সদস্য, তারা সবাই পড়তে পারবে)",
  "platform.account.suspend": "সব জায়গায় স্থগিত করুন",
  "platform.account.reinstate": "পুনর্বহাল করুন",
  "platform.account.denies": "প্ল্যাটফর্ম দ্বারা প্রত্যাখ্যাত",
  "platform.account.denies.none": "প্ল্যাটফর্ম কিছুই প্রত্যাখ্যান করেনি।",
  "platform.account.clear": "মুছুন",
  "platform.account.deny": "প্রত্যাখ্যান করুন",
  "platform.account.deny.organization": "প্রতিষ্ঠানে",
  "platform.account.denied": "প্রত্যাখ্যাত: {permissions}",
} as const;
