import type { NamespaceBundle } from "../namespace.js";

// Total, not partial: `NamespaceBundle` is a `Record`, so an `en` key added without a
// translation fails `tsc` rather than rendering an English sentence on a Bengali page.
export const role: NamespaceBundle<"role"> = {
  "role.title": "ভূমিকা",
  "role.subtitle": "এই প্রতিষ্ঠানে প্রতিটি ভূমিকা কী করতে পারে।",
  "role.column.permission": "অনুমতি",
  "role.column.name": "ভূমিকা",
  "role.column.actions": "কার্যক্রম",
  "role.badge.system": "অন্তর্নির্মিত",
  "role.hint.owner": "মালিক ভূমিকাটি নতুনগুলি সহ প্রতিটি অনুমতি পায়।",
  "role.hint.system": "অন্তর্নির্মিত ভূমিকা প্রতিটি স্থাপনায় পুনরায় লেখা হয়, তাই সম্পাদনা করা যায় না।",
  "role.hint.readOnly": "আপনি এই অনুমতিগুলি দেখতে পারেন, পরিবর্তন করতে পারেন না।",
  "role.blocked": "আপনার প্ল্যানে অন্তর্ভুক্ত নয়",
  "role.empty": "এখনও কোনো ভূমিকা নেই। অন্তর্নির্মিত চারটি তৈরি করতে `pnpm db:seed` চালান।",
  "role.create.title": "নতুন ভূমিকা",
  "role.create.key": "কী",
  "role.create.keyHint": "ছোট হাতের অক্ষর, সংখ্যা, ড্যাশ। তৈরি হলে আর বদলানো যাবে না।",
  "role.create.name": "নাম",
  "role.create.description": "বিবরণ",
  "role.create.submit": "ভূমিকা তৈরি করুন",
  "role.rename.title": "{name} নাম বদলান",
  "role.action.rename": "নাম বদলান",
  "role.action.delete": "মুছুন",
  "role.action.save": "সংরক্ষণ",
  "role.action.cancel": "বাতিল",
  "role.error.reserved": "এই কী একটি অন্তর্নির্মিত ভূমিকার। অন্য একটি বেছে নিন।",
  "role.error.duplicate": "এই কী দিয়ে একটি ভূমিকা এখানে আগে থেকেই আছে।",
  "role.error.system": "অন্তর্নির্মিত ভূমিকা সম্পাদনা বা মুছে ফেলা যায় না।",
  "role.error.inUse": "কেউ এখনও এই ভূমিকায় আছেন। আগে তাঁকে অন্য ভূমিকায় সরান।",
  "role.error.escalate": "আপনি নিজে যে অনুমতি রাখেন না, তা অন্যকে দিতে পারবেন না।",

  "role.override.title": "ব্যতিক্রম",
  "role.override.empty": "কোনোটি নয় — এই ব্যক্তি তার ভূমিকা যা দেয় ঠিক তাই পান।",
  "role.override.granted": "দেওয়া হয়েছে",
  "role.override.denied": "নিষেধ",
  "role.override.until": "{date} পর্যন্ত",
  "role.override.platform": "প্ল্যাটফর্ম নির্ধারিত — সহায়তার সাথে যোগাযোগ করুন",
  "role.override.clear": "মুছুন",
  "role.override.form.title": "ব্যতিক্রম যোগ করুন",
  "role.override.form.permission": "অনুমতি",
  "role.override.form.effect": "প্রভাব",
  "role.override.form.grant": "দিন, একটি তারিখ পর্যন্ত",
  "role.override.form.deny": "নিষেধ করুন, স্থায়ীভাবে",
  "role.override.form.reason": "কারণ",
  "role.override.form.expires": "পর্যন্ত (সর্বোচ্চ ৯০ দিন; ৩০ দিনের জন্য খালি রাখুন)",
  "role.override.form.submit": "ব্যতিক্রম যোগ করুন",
  "role.override.written": "পরিবর্তিত: {permissions}",
  "role.source.role": "তার ভূমিকা থেকে",
  "role.source.override": "একটি ব্যতিক্রম",
  "role.source.denied": "একটি ব্যতিক্রমে নিষিদ্ধ",
  "role.source.platform": "প্ল্যাটফর্মে নিষিদ্ধ",
  "role.source.plan": "আপনার প্ল্যানে নেই",
  "role.exceptions.one": "১ জন সদস্যের ব্যতিক্রম আছে",
  "role.exceptions.other": "{count} জন সদস্যের ব্যতিক্রম আছে",
};
