export const widget = {
  "widget.zone.dashboard.main": "ড্যাশবোর্ড",
  "widget.zone.empty": "এখানে এখনও দেখানোর মতো কিছু নেই।",
  "widget.core.module-nav.title": "যান",
  "widget.member.count.title": "সদস্য",
  "widget.notification.bell.title": "বিজ্ঞপ্তি",
  "widget.core.hidden-widgets.title": "লুকানো কার্ড",
  "widget.hide": "লুকান",
  "widget.hideCard": "{title} লুকান",
  "widget.restore": "আবার দেখান",
  "widget.restoreCard": "{title} আবার দেখান",
  "widget.hidden.none": "কোনো কার্ড লুকানো নেই।",
  "widget.hidden.byAdmin": "আপনার প্রতিষ্ঠান সবার জন্য লুকিয়েছে",
  "widget.defaults.title": "ড্যাশবোর্ড কার্ড",
  "widget.defaults.description":
    "এই প্রতিষ্ঠানের সবার জন্য একটি কার্ড লুকান। কার্ড লুকানো মানে অ্যাক্সেস সরানো নয়: যার এর তথ্য দেখার অনুমতি আছে, সে এক লিঙ্ক দূরেই তা দেখতে পায়।",
  "widget.defaults.unavailable": "এই প্রতিষ্ঠানে কার্ড লুকানো এখনও চালু হয়নি।",
  "widget.defaults.hidden": "সবার জন্য লুকানো",
  "widget.defaults.shown": "দেখানো হচ্ছে",
  "widget.defaults.hide": "সবার জন্য লুকান",
  "widget.defaults.show": "সবাইকে দেখান",
  "widget.inspector.title": "ড্যাশবোর্ড কার্ড, এবং প্রতিটি কেন দেখানো হচ্ছে বা হচ্ছে না",
  "widget.inspector.column.card": "কার্ড",
  "widget.inspector.column.answer": "উত্তর",
  "widget.reason.disclosure": "কিছু দেখা যাচ্ছে না কেন?",
  "widget.reason.visible": "দেখানো হচ্ছে।",
  "widget.reason.hidden-by-flag": "এই প্রতিষ্ঠানে এখনও চালু হয়নি।",
  "widget.reason.denied": "{permission} অনুমতি প্রয়োজন।",
  "widget.reason.hidden-by-admin": "একজন অ্যাডমিন সবার জন্য লুকিয়েছেন।",
  "widget.reason.hidden-by-user": "ইচ্ছাকৃতভাবে লুকানো। লুকানো কার্ড থেকে আবার দেখানো যায়।",
  "widget.reason.unregistered": "একটি সংরক্ষিত পছন্দ এমন একটি কার্ডের নাম দেয় যা আর নেই।",
} as const;
