// Everything this package takes from outside itself. The longest `import.ts` here, and
// that is the package working: wiring names both sides exactly once.

// ── @loadbearing/application ─────────────────────────────────────────────────
export {
  ActivityLogger,
  ActivityRelaySubscriber,
  AdjustEntitlementUseCase,
  type ArchivedObject,
  type ArchivedPartition,
  AssignPlanUseCase,
  Authorizer,
  CacheStore,
  type CancellationSignal,
  CapabilityInvalidator,
  ChangeMemberRoleUseCase,
  ClearAccountDenyUseCase,
  ClearEntitlementAdjustmentUseCase,
  ClearPermissionOverrideUseCase,
  ColdArchiveReader,
  type ColdPage,
  type ColdTier,
  CountUnreadNotificationsUseCase,
  CreateApiKeyUseCase,
  CreateDocPageUseCase,
  CreateDocSpaceUseCase,
  CreateRoleUseCase,
  DeleteDocPageUseCase,
  DeleteDocSpaceUseCase,
  type DeletedTenantSweep,
  DeleteOrganizationUseCase,
  DeletePlanUseCase,
  DeleteRoleUseCase,
  DeliverNotificationUseCase,
  DenyAccountPermissionUseCase,
  DenyPermissionOverrideUseCase,
  DocAccess,
  DocCache,
  DocImageSweep,
  DocSearch,
  DocTree,
  type DocumentChunk,
  DomainEventPublisher,
  type EmailMessage,
  type EmailReceipt,
  EmailSender,
  EmbeddingProvider,
  EventSubscriber,
  ExpireEntitlementAdjustmentsUseCase,
  ExpirePermissionOverridesUseCase,
  type ExportedObject,
  ExportOrganizationUseCase,
  FindAccountUseCase,
  FlagCache,
  type FlagRecord,
  FlagRepository,
  GetDocPageUseCase,
  GetDocRevisionUseCase,
  GetDocSpaceUseCase,
  GetEntitlementUseCase,
  GetNotificationPreferencesUseCase,
  GetOrganizationEntitlementUseCase,
  GrantPermissionOverrideUseCase,
  GrantPermissionUseCase,
  IndexDocumentUseCase,
  type IndexedSource,
  InspectEffectivePermissionsUseCase,
  InspectPlatformStatusUseCase,
  type InvitationMail,
  InvitationMailer,
  InviteMemberUseCase,
  type JobOptions,
  type LifecycleRule,
  ListApiKeysUseCase,
  ListArchivedNotificationsUseCase,
  ListDocGrantsUseCase,
  ListDocPagesUseCase,
  ListDocRevisionsUseCase,
  ListDocSpacesUseCase,
  ListFlagsUseCase,
  ListInvitationsUseCase,
  ListMembersUseCase,
  ListModuleSwitchesUseCase,
  ListNotificationsUseCase,
  ListPermissionOverridesUseCase,
  ListPlansUseCase,
  ListPlatformDocSpacesUseCase,
  ListRolesUseCase,
  ListTenantExportsUseCase,
  type LogEntry,
  type LogQuery,
  LogReader,
  MailPublisher,
  MailRenderer,
  type MailRequest,
  MaintenanceGateway,
  MarkAllNotificationsReadUseCase,
  MarkdownRenderer,
  MarkNotificationReadUseCase,
  MemberRealtimeSubscriber,
  MoveDocPageUseCase,
  NotificationSubscriber,
  OpenDocImageUseCase,
  OrganizationReader,
  OutboxGateway,
  type PartitionArchiveEntry,
  PartitionArchiveGateway,
  type PartitionEstimate,
  type PartitionedTableName,
  type PlatformHealth,
  PlatformHealthReader,
  type PlatformPolicyRecord,
  PlatformPolicyRepository,
  PlatformReader,
  type PlatformStatus,
  PreviewDocPageUseCase,
  // A value: `placedAt` builds the empty principal a placement-only read needs.
  Principal,
  type ProjectionGap,
  PublishDocPageUseCase,
  PurgeOrganizationUseCase,
  QueueDocumentIndexUseCase,
  QueueName,
  QueuePublisher,
  RateLimitStore,
  ReadDocPageUseCase,
  ReadPlatformDocUseCase,
  type RealtimeChannel,
  RealtimeChannels,
  RealtimePublisher,
  RealtimeSubscriber,
  ReinstateAccountUseCase,
  type RelayedActivity,
  RelayedActivityStore,
  type RenderedMail,
  type RenderedMarkdown,
  type ReplicaHealthReport,
  type RequestHeaders,
  ResendInvitationUseCase,
  type ResolvedSession,
  RestoreDocRevisionUseCase,
  type RestoredMonth,
  type RetentionPolicyRecord,
  RetentionPolicyRepository,
  RetentionRules,
  type RetentionStore,
  RevokeApiKeyUseCase,
  RevokeDocGrantUseCase,
  RevokeInvitationUseCase,
  RevokePermissionUseCase,
  type RoleRecord,
  RoleRepository,
  SaveDocGrantUseCase,
  SaveDocPageUseCase,
  SavePlanUseCase,
  SearchDocsUseCase,
  SearchDocumentsUseCase,
  type SearchHit,
  SearchPlatformDocsUseCase,
  SendMailUseCase,
  SendNotificationDigestUseCase,
  SessionGateway,
  SessionResolver,
  SetMemberActiveUseCase,
  Shard,
  ShardingStrategy,
  type ShardKey,
  type ShardPlacement,
  ShardResolver,
  StorageGateway,
  StoragePolicyGateway,
  type StoredObject,
  type SubscribeOptions,
  SubscriberRegistry,
  SuspendAccountUseCase,
  type SweepOutcome,
  SwitchModuleUseCase,
  type TenantExport,
  TenantMembershipReader,
  type TenantRetentionPolicyRecord,
  TenantRetentionPolicyRepository,
  type TenantRunway,
  ToggleReplicaReadsUseCase,
  UnitOfWork,
  UpdateDefaultPlanUseCase,
  UpdateDocSpaceUseCase,
  UpdateFlagTargetUseCase,
  UpdateFlagUseCase,
  UpdateNotificationPreferenceUseCase,
  UpdateRoleUseCase,
  UploadDocImageUseCase,
  UserReader,
  VectorStore,
} from "@loadbearing/application";

// ── @loadbearing/auth ────────────────────────────────────────────────────────
export {
  ApiKeyResolver,
  AuthFactory,
  type AuthInstance,
  AuthMailer,
  BetterAuthSessionGateway,
  BetterAuthSessionResolver,
  CapabilityCache,
  type InvitationClaimer,
  InvitationClaimingEnroller,
  type MailRecipient,
  type MembershipEnroller,
  type MembershipReader,
  NullMembershipEnroller,
  type OrganizationFounder,
  PrincipalBuilder,
} from "@loadbearing/auth";

// ── @loadbearing/content ─────────────────────────────────────────────────────
export {
  type ContentSource,
  type Locale,
  Locales,
  SERVER_CATALOG,
  StaticContentSource,
  type Translator,
} from "@loadbearing/content";

// ── @loadbearing/contracts ─────────────────────────────────────────────
// Only the branded ids two port signatures name, without which `test-container.ts`
// cannot override them.
export type {
  DomainEvent,
  DomainEventInput,
  DomainEventName,
  GoalId,
  MailTemplateKey,
  MailTemplateParams,
  OrganizationId,
  PaginationQuery,
  RealtimeMessage,
  UserId,
} from "@loadbearing/contracts";

// ── @loadbearing/core ────────────────────────────────────────────────────────
export { type Clock, FixedClock, ServerOnly, SystemClock, Uuid } from "@loadbearing/core";

// ── @loadbearing/errors ──────────────────────────────────────────────────────
export { ConflictError, NotFoundError } from "@loadbearing/errors";

// ── @loadbearing/infrastructure ──────────────────────────────────────────────
// Every concrete adapter, Postgres included — one block, because one package holds the
// whole outside-world side of the ports below.
export {
  BullMqQueuePublisher,
  Database,
  DatabaseCluster,
  type DatabaseStats,
  LokiLogReader,
  OpenAiEmbeddingProvider,
  OrdinalCursor,
  PgAccountRepository,
  PgActivityLogger,
  PgApiKeyRepository,
  PgBootstrapMembershipEnroller,
  PgCapabilityRepository,
  PgDocGrantRepository,
  PgDocPageRepository,
  PgDocSpaceRepository,
  PgEntitlementRepository,
  PgFlagRepository,
  PgInvitationClaimer,
  PgInvitationRepository,
  PgMaintenanceGateway,
  PgMemberRepository,
  PgMembershipReader,
  PgNotificationPreferenceRepository,
  PgNotificationRecipientReader,
  PgNotificationRepository,
  PgOrganizationFounder,
  PgOrganizationReader,
  PgOutboxGateway,
  PgOutboxPublisher,
  PgPartitionArchiveGateway,
  PgPermissionOverrideRepository,
  PgPersonalOrganizationEnroller,
  PgPlatformPolicyRepository,
  PgPlatformReader,
  PgRetentionPolicyRepository,
  PgRoleRepository,
  PgShardMapReader,
  PgShardResolver,
  PgTenantRepository,
  PgTenantRetentionPolicyRepository,
  PgUnitOfWork,
  PgVectorStore,
  RedisCacheStore,
  RedisConnection,
  RedisRateLimitStore,
  RedisRealtimePublisher,
  RedisRealtimeSubscriber,
  type ReplicaHealth,
  S3ColdArchiveReader,
  S3StorageGateway,
  S3StoragePolicyGateway,
  type ShardConfig,
  ShardScope,
  SmtpEmailSender,
  TransactionScope,
  UnifiedMarkdownRenderer,
} from "@loadbearing/infrastructure";

// ── @loadbearing/observability ───────────────────────────────────────────────
export { JsonLogger, type Logger, type LogLevel, SilentLogger } from "@loadbearing/observability";

// ── @loadbearing/permissions ─────────────────────────────────────────────────
// Only the route table, so the invitation mail's link and the landing page spell the
// same literal.
export { CapabilitySet, ROUTES } from "@loadbearing/permissions";
