// Everything this package takes from outside itself. The longest `import.ts` here, and
// that is the package working: wiring names both sides exactly once.

// ── @loadbearing/application ─────────────────────────────────────────────────
export {
  ActivityLogger,
  ActivityRelaySubscriber,
  AddMemberDomainUseCase,
  AddTeamMemberUseCase,
  AdjustEntitlementUseCase,
  type ArchivedObject,
  type ArchivedPartition,
  AssignPlanUseCase,
  Authorizer,
  BindGithubInstallationUseCase,
  CacheStore,
  type CancellationSignal,
  CapabilityInvalidator,
  ChangeMemberRoleUseCase,
  CheckoutScanUseCase,
  ClearAccountDenyUseCase,
  ClearEntitlementAdjustmentUseCase,
  ClearPermissionOverrideUseCase,
  CompleteScanUseCase,
  CountUnreadNotificationsUseCase,
  CreateApiKeyUseCase,
  CreateDocPageUseCase,
  CreateDocSpaceUseCase,
  CreateInvitationLinkUseCase,
  CreateProjectUseCase,
  CreateRoleUseCase,
  CreateScanUploadUseCase,
  CreateTeamUseCase,
  DeleteDocPageUseCase,
  DeleteDocSpaceUseCase,
  type DeletedTenantSweep,
  DeleteOrganizationUseCase,
  DeletePlanUseCase,
  DeleteRoleUseCase,
  DeliverNotificationUseCase,
  DenyAccountPermissionUseCase,
  DenyPermissionOverrideUseCase,
  DispatchScanUseCase,
  DocAccess,
  DocCache,
  DocFeaturePolicy,
  DocImageSweep,
  DocRerender,
  DocSearch,
  DocTree,
  type DocumentChunk,
  DomainEventPublisher,
  type EmailMessage,
  type EmailReceipt,
  EmailSender,
  EmbeddingProvider,
  EventSubscriber,
  ExpireEntitlementAdjustmentsUseCase,
  ExpirePermissionOverridesUseCase,
  type ExportedObject,
  ExportOrganizationUseCase,
  FailScanUseCase,
  FindAccountUseCase,
  FlagCache,
  type FlagRecord,
  FlagRepository,
  GetDocPageUseCase,
  GetDocRevisionUseCase,
  GetDocSpaceUseCase,
  GetEntitlementUseCase,
  GetGithubStatusUseCase,
  GetGraphUseCase,
  GetNotificationPreferencesUseCase,
  GetOrganizationEntitlementUseCase,
  GetOrganizationUseCase,
  GetProjectAccessOverviewUseCase,
  GetProjectUseCase,
  type GithubInstallationRepository,
  type GithubWebhookEvent,
  GrantPermissionOverrideUseCase,
  GrantPermissionUseCase,
  HandleGithubWebhookUseCase,
  IndexDocumentUseCase,
  type IndexedSource,
  InspectEffectivePermissionsUseCase,
  InspectPlatformStatusUseCase,
  type InvitationMail,
  InvitationMailer,
  InviteMemberUseCase,
  type JobOptions,
  type LifecycleRule,
  ListActivityUseCase,
  ListApiKeysUseCase,
  ListAvailableRepositoriesUseCase,
  ListDocAccessOptionsUseCase,
  ListDocGrantsUseCase,
  ListDocPagesUseCase,
  ListDocRevisionsUseCase,
  ListDocSpacesUseCase,
  ListFlagsUseCase,
  ListInvitationLinksUseCase,
  ListInvitationsUseCase,
  ListMemberDomainsUseCase,
  ListMembersUseCase,
  ListModuleSwitchesUseCase,
  ListNotificationsUseCase,
  ListPermissionOverridesUseCase,
  ListPlansUseCase,
  ListPlatformDocSpacesUseCase,
  ListProjectsUseCase,
  ListRolesUseCase,
  ListScansUseCase,
  ListTeamMembersUseCase,
  ListTeamsUseCase,
  ListTenantExportsUseCase,
  MailPublisher,
  MailRenderer,
  type MailRequest,
  MaintenanceGateway,
  ManageProjectAccessUseCase,
  ManageProjectRepositoryUseCase,
  ManageViewsUseCase,
  MarkAllNotificationsReadUseCase,
  MarkdownRenderer,
  MarkNotificationReadUseCase,
  MemberRealtimeSubscriber,
  MoveDocPageUseCase,
  NotificationSubscriber,
  OpenDocImageUseCase,
  OrganizationReader,
  OutboxGateway,
  PartitionArchiveGateway,
  type PartitionEstimate,
  PartitionedTable,
  type PartitionedTableEntry,
  type PartitionedTableName,
  type PlatformHealth,
  PlatformHealthReader,
  type PlatformPolicyRecord,
  PlatformPolicyRepository,
  PlatformReader,
  type PlatformStatus,
  PreviewDocPageUseCase,
  Principal,
  type ProjectRepository,
  type ProviderInstallation,
  type ProviderRepository,
  PublishDocPageUseCase,
  PurgeOrganizationUseCase,
  PurgeProjectUseCase,
  QueueDocumentIndexUseCase,
  QueueName,
  QueuePublisher,
  QueueScanUseCase,
  RateLimitStore,
  ReadDocNavUseCase,
  ReadDocPageUseCase,
  ReadPlatformDocNavUseCase,
  ReadPlatformDocUseCase,
  type RealtimeChannel,
  RealtimeChannels,
  RealtimePublisher,
  RealtimeSubscriber,
  ReembedChunksUseCase,
  ReinstateAccountUseCase,
  type RelayedActivity,
  RelayedActivityStore,
  RemoveMemberDomainUseCase,
  RemoveMemberUseCase,
  RemoveOrganizationUseCase,
  RemoveProjectUseCase,
  RemoveTeamMemberUseCase,
  RemoveTeamUseCase,
  type RenderedMail,
  type RenderedMarkdown,
  type ReplicaHealthReport,
  RepositoryProvider,
  type RequestHeaders,
  ResendInvitationUseCase,
  type ResolvedSession,
  RestoreDocRevisionUseCase,
  RetentionRules,
  RevokeApiKeyUseCase,
  RevokeDocGrantUseCase,
  RevokeInvitationLinkUseCase,
  RevokeInvitationUseCase,
  RevokePermissionUseCase,
  type RoleRecord,
  RoleRepository,
  RunScanUseCase,
  SaveDocGrantUseCase,
  SaveDocPageUseCase,
  SavePlanUseCase,
  type ScanCheckout,
  type ScanRef,
  ScanRefs,
  SearchDocsUseCase,
  SearchDocumentsUseCase,
  type SearchHit,
  type SearchMode,
  SearchPlatformDocsUseCase,
  SendMailUseCase,
  SendNotificationDigestUseCase,
  SessionGateway,
  SessionResolver,
  SetMemberActiveUseCase,
  Shard,
  ShardingStrategy,
  type ShardKey,
  type ShardPlacement,
  ShardResolver,
  type StaleChunk,
  StorageGateway,
  StoragePolicyGateway,
  type StoredObject,
  type SubscribeOptions,
  SubscriberRegistry,
  SuspendAccountUseCase,
  type SweepOutcome,
  SweepScansUseCase,
  SwitchModuleUseCase,
  type TenantExport,
  TenantMembershipReader,
  type TenantRunway,
  ToggleReplicaReadsUseCase,
  TransferOwnershipUseCase,
  TriggerScanUseCase,
  UnitOfWork,
  UpdateDefaultPlanUseCase,
  UpdateDocSpaceUseCase,
  UpdateFlagTargetUseCase,
  UpdateFlagUseCase,
  UpdateNotificationPreferenceUseCase,
  UpdateOrganizationUseCase,
  UpdateProjectUseCase,
  UpdateRoleUseCase,
  UpdateTeamUseCase,
  UploadDocImageUseCase,
  UploadScanUseCase,
  UserReader,
  VectorStore,
} from "@loadbearing/application";

// ── @loadbearing/auth ────────────────────────────────────────────────────────
export {
  ApiKeyResolver,
  AuthFactory,
  type AuthInstance,
  AuthMailer,
  BetterAuthSessionGateway,
  BetterAuthSessionResolver,
  CapabilityCache,
  DomainJoiningEnroller,
  type InvitationClaimer,
  InvitationClaimingEnroller,
  type MailRecipient,
  type MemberDomainClaimer,
  type MembershipEnroller,
  type MembershipReader,
  NullMembershipEnroller,
  type OrganizationFounder,
  PrincipalBuilder,
} from "@loadbearing/auth";

// ── @loadbearing/content ─────────────────────────────────────────────────────
export {
  type ContentSource,
  type Locale,
  Locales,
  SERVER_CATALOG,
  StaticContentSource,
  type Translator,
} from "@loadbearing/content";

// ── @loadbearing/contracts ─────────────────────────────────────────────
// Only the branded ids two port signatures name, without which `test-container.ts`
// cannot override them.
export type {
  DomainEvent,
  DomainEventInput,
  DomainEventName,
  GoalId,
  MailTemplateKey,
  MailTemplateParams,
  OrganizationId,
  PaginationQuery,
  ProjectId,
  RealtimeMessage,
  ScanId,
  UserId,
} from "@loadbearing/contracts";
// A queued `deliver` job crosses the wire as JSON and is parsed back into a typed event.
export { DomainEvents } from "@loadbearing/contracts";

// ── @loadbearing/core ────────────────────────────────────────────────────────
export { type Clock, FixedClock, ServerOnly, SystemClock, Uuid } from "@loadbearing/core";

// ── @loadbearing/errors ──────────────────────────────────────────────────────
export { ConflictError, NotFoundError } from "@loadbearing/errors";

// ── @loadbearing/infrastructure ──────────────────────────────────────────────
// Every concrete adapter, Postgres included — one block, because one package holds the
// whole outside-world side of the ports below.
export {
  BullMqQueuePublisher,
  CloudflareQueuePublisher,
  Database,
  DatabaseCluster,
  type DatabaseStats,
  GeminiEmbeddingProvider,
  GithubActionsScanRunner,
  GithubAppProvider,
  HmacScanTokens,
  JobSignatureHasher,
  LocalScanRunner,
  NullRepositoryProvider,
  NullScanRunner,
  OpenAiEmbeddingProvider,
  PgAccountRepository,
  PgActivityLogger,
  PgActivityReader,
  PgApiKeyRepository,
  PgBootstrapMembershipEnroller,
  PgCapabilityRepository,
  PgDocGrantRepository,
  PgDocPageRepository,
  PgDocSpaceRepository,
  PgEntitlementRepository,
  PgFlagRepository,
  PgGithubInstallationRepository,
  PgGraphViewRepository,
  PgInvitationClaimer,
  PgInvitationLinkClaimer,
  PgInvitationLinkRepository,
  PgInvitationRepository,
  PgMaintenanceGateway,
  PgMemberDomainClaimer,
  PgMemberDomainRepository,
  PgMemberRepository,
  PgMembershipReader,
  PgNotificationPreferenceRepository,
  PgNotificationRecipientReader,
  PgNotificationRepository,
  PgOrganizationFounder,
  PgOrganizationReader,
  PgOrganizationRepository,
  PgOutboxGateway,
  PgOutboxPublisher,
  PgPartitionArchiveGateway,
  PgPermissionOverrideRepository,
  PgPersonalOrganizationEnroller,
  PgPlatformPolicyRepository,
  PgPlatformReader,
  PgProjectRepository,
  PgRoleRepository,
  PgScanRepository,
  PgShardMapReader,
  PgShardResolver,
  PgTeamRepository,
  PgTenantRepository,
  PgUnitOfWork,
  PgUserReader,
  PgVectorStore,
  RedisCacheStore,
  RedisConnection,
  RedisRateLimitStore,
  RedisRealtimePublisher,
  RedisRealtimeSubscriber,
  type ReplicaHealth,
  S3StorageGateway,
  S3StoragePolicyGateway,
  type ShardConfig,
  ShardScope,
  SmtpEmailSender,
  StorageGraphArchive,
  TransactionScope,
  UnifiedMarkdownRenderer,
} from "@loadbearing/infrastructure";

// ── @loadbearing/observability ───────────────────────────────────────────────
export { JsonLogger, type Logger, type LogLevel, SilentLogger } from "@loadbearing/observability";

// ── @loadbearing/permissions ─────────────────────────────────────────────────
// Only the route table, so the invitation mail's link and the landing page spell the
// same literal.
export {
  CapabilitySet,
  type PermissionKey,
  PermissionRegistry,
  ROUTES,
} from "@loadbearing/permissions";
