import type { ConversationId, MessageId, OrganizationId, UserId } from "../import.js";

export interface MessageRecord {
  readonly id: MessageId;
  readonly conversationId: ConversationId;
  readonly authorId: UserId;
  readonly clientId: string;
  readonly body: string;
  readonly deleted: boolean;
  readonly editedAt: Date | null;
  readonly createdAt: Date;
}

export interface MessagePageResult {
  readonly items: readonly MessageRecord[];
  readonly olderCursor: string | null;
}

export interface MessageQuery {
  readonly conversationId: ConversationId;
  readonly limit: number;
  readonly before?: string | undefined;
  // The newest row's `created_at`, if known: an upper bound the first page can prune by.
  readonly upTo?: Date | undefined;
}

export interface NewMessage {
  // Generated by the use-case, not here: the send dedupe holds them, which is what lets
  // a retry be handed back the row the first attempt wrote.
  readonly id: MessageId;
  readonly createdAt: Date;
  readonly organizationId: OrganizationId;
  readonly conversationId: ConversationId;
  readonly authorId: UserId;
  readonly clientId: string;
  readonly body: string;
}

export interface UnreadCount {
  readonly conversationId: ConversationId;
  readonly count: number;
}

export abstract class MessageRepository {
  // Pages backwards from the newest, which is the direction a conversation is read.
  public abstract list(
    organizationId: OrganizationId,
    query: MessageQuery,
  ): Promise<MessagePageResult>;

  // `createdAt` is the partition hint everywhere else; here it keeps the same shape so a
  // caller does not have to know which tables are partitioned and which are not.
  public abstract findById(
    organizationId: OrganizationId,
    conversationId: ConversationId,
    messageId: MessageId,
    createdAt: Date,
  ): Promise<MessageRecord | null>;

  // A plain insert. The dedupe that used to live on a unique index here is a Redis key
  // the use-case holds — a partitioned table cannot carry that index. See messaging.md.
  public abstract save(message: NewMessage): Promise<MessageRecord>;

  public abstract edit(
    organizationId: OrganizationId,
    messageId: MessageId,
    createdAt: Date,
    body: string,
    at: Date,
  ): Promise<MessageRecord | null>;

  // Soft: the row keeps its place so the keyset cursor over the conversation stays
  // stable, and the body is blanked rather than the row removed.
  public abstract softDelete(
    organizationId: OrganizationId,
    messageId: MessageId,
    createdAt: Date,
    at: Date,
  ): Promise<void>;

  // One statement for the whole page, capped. There is no counter column to drift —
  // `last_read_at` is the only state. See docs/reference/messaging.md.
  public abstract unreadCounts(
    organizationId: OrganizationId,
    userId: UserId,
    conversationIds: readonly ConversationId[],
  ): Promise<readonly UnreadCount[]>;
}
