-- The condition `0025` set, met. That migration carried every row across to
-- `partition_archive` and then said this table stays "until no deployment can still hold
-- objects under the old `activity-archive/` prefix".
--
-- There is no deployment. CI builds and tests and does not deploy, there are no tags and
-- no releases, and the only bucket this system has ever written to holds `cold/` and
-- `export/` and nothing else. So no object can be orphaned by this, because no object
-- under that prefix exists anywhere to orphan.
--
-- `CASCADE` is drizzle-kit's, and it drops nothing: no foreign key points at this table
-- and no view reads it. `partition_archive` covers every partitioned table where this
-- covered one, and its assertion-9 exemption goes with it: `shard.ts` no longer names it.
DROP TABLE "activity_archive" CASCADE;