// The only `import.ts` allowed to name the cache library — and never the router from the
// same vendor, which is what lets a second shell reuse this package.

// ── @loadbearing/api-client ──────────────────────────────────────────────────
export type {
  AccountClient,
  ActiveSession,
  ApiClient,
  AuthClient,
  LinkedAccount,
  OrganizationClient,
  OrganizationSwitch,
  TwoFactorEnrolment,
} from "@loadbearing/api-client";

// ── @loadbearing/contracts ───────────────────────────────────────────────────
// Types only: this package caches what the contract describes, with no opinion about it.
export type {
  AccountDenyClearInput,
  AccountDenySaveInput,
  AccountDto,
  AccountSuspensionInput,
  AdjustedDto,
  AdjustmentClearInput,
  AdjustmentSaveInput,
  ApiKeyDto,
  ArchivedNotificationQuery,
  ChangeMemberRoleInput,
  ChangeRolePermissionInput,
  ClearOverrideInput,
  CreateApiKeyInput,
  CreateDocPageInput,
  CreateDocSpaceInput,
  CreatedApiKeyDto,
  CreateRoleInput,
  DeleteRequestedDto,
  DeleteRoleInput,
  DenyOverrideInput,
  DocGrantDto,
  DocGrantListDto,
  DocImageType,
  DocPageDraftDto,
  DocPageId,
  DocPageRefInput,
  DocPageTreeDto,
  DocReadingDto,
  DocRevisionDto,
  DocRevisionListDto,
  DocSpaceDto,
  DocSpaceId,
  DocSpaceListDto,
  DocSpaceRefInput,
  DocumentHitDto,
  ExportRequestedDto,
  FlagTargetToggleInput,
  FlagToggleInput,
  GrantOverrideInput,
  IndexDocumentContractInput,
  InvitationDto,
  InviteMemberInput,
  ListNotificationsInput,
  MarkNotificationReadInput,
  MemberDto,
  ModuleSwitchUpdateInput,
  MoveDocPageInput,
  NotificationDto,
  OrganizationId,
  OverrideWrittenDto,
  PaginationQuery,
  PlanAssignInput,
  PlanRefInput,
  PlanSaveInput,
  PreviewDocPageInput,
  PublishDocPageInput,
  QueuedDocumentDto,
  RealtimeEventName,
  RealtimeMessage,
  RenderedDocDto,
  ReplicaToggleInput,
  ResendInvitationInput,
  RestoreDocRevisionInput,
  RevokeApiKeyInput,
  RevokeDocGrantInput,
  RevokeInvitationInput,
  RoleDto,
  SaveDocGrantInput,
  SaveDocPageInput,
  SearchDocumentsContractInput,
  SetMemberActiveInput,
  TenantDeleteInput,
  TenantExportInput,
  UpdateDocSpaceInput,
  UpdateNotificationPreferenceInput,
  UpdateRoleInput,
} from "@loadbearing/contracts";

// ── @loadbearing/errors ──────────────────────────────────────────────────────
// Retryability is a fact about the code, declared once in the catalog and read here.
export { ERROR_CATALOG, ErrorNormalizer } from "@loadbearing/errors";

// ── @tanstack/react-query ────────────────────────────────────────────────────
export {
  type InfiniteData,
  infiniteQueryOptions,
  QueryClient,
  type QueryKey,
  queryOptions,
  type UseInfiniteQueryOptions,
  type UseInfiniteQueryResult,
  type UseMutationOptions,
  type UseQueryOptions,
  type UseQueryResult,
  useInfiniteQuery,
  useMutation,
  useQuery,
  useQueryClient,
} from "@tanstack/react-query";

// ── react ────────────────────────────────────────────────────────────────────
export {
  createContext,
  type ReactNode,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
