// Compiles src/icon/svg/*.svg into one sprite plus the IconName union that indexes it.
// Runs as `prebuild`, so `pnpm build` cannot produce a package whose registry disagrees
// with the files on disk.

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";

const SOURCE = "src/icon/svg";
const OUTPUT = "src/icon/sprite.svg";
const REGISTRY = "src/icon/icon-registry.ts";
const FONT_CSS = "src/font/font.css";

const files = readdirSync(SOURCE)
  .filter((file) => file.endsWith(".svg"))
  .sort();

const symbols = [];
const names = [];
const problems = [];

for (const file of files) {
  const name = basename(file, ".svg");
  const raw = readFileSync(join(SOURCE, file), "utf8");

  // A hardcoded colour produces an icon that is invisible in dark mode and goes
  // unnoticed for weeks. Fail the build instead.
  if (/(fill|stroke)=["'](?!none|currentColor)[^"']+["']/.test(raw)) {
    problems.push(`${file}: hardcoded fill or stroke — use currentColor`);
    continue;
  }

  // Without one the symbol has no coordinate system and renders at whatever size the
  // first <use> happens to imply, which differs per call site.
  const viewBox = /viewBox=["']([^"']+)["']/.exec(raw)?.[1];
  if (!viewBox) {
    problems.push(`${file}: missing viewBox`);
    continue;
  }

  const body = raw
    .replace(/<\?xml[^>]*\?>/g, "")
    .replace(/<svg[^>]*>/, "")
    .replace(/<\/svg>/, "")
    .trim();

  symbols.push(`  <symbol id="${name}" viewBox="${viewBox}">${body}</symbol>`);
  names.push(name);
}

if (problems.length > 0) {
  console.error(`Icon sprite build failed:\n${problems.map((p) => `  - ${p}`).join("\n")}`);
  process.exit(1);
}

writeFileSync(
  OUTPUT,
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n${symbols.join("\n")}\n</svg>\n`,
);

// Biome collapses an array literal onto one line when it fits inside `lineWidth`, and
// expands it one entry per line when it does not. Emitting anything else means every icon
// addition shows up twice — once here, and again as a reformat on the next `pnpm check`.
const inline = `export const ICON_NAMES = [${names.map((n) => `"${n}"`).join(", ")}] as const;`;
const declaration =
  inline.length <= 100
    ? inline
    : `export const ICON_NAMES = [\n${names.map((n) => `  "${n}",`).join("\n")}\n] as const;`;

writeFileSync(
  REGISTRY,
  `// Generated by build-sprite.mjs. Do not edit.
${declaration}

export type IconName = (typeof ICON_NAMES)[number];

export class IconRegistry {
  private constructor() {}

  public static all(): readonly IconName[] {
    return ICON_NAMES;
  }

  public static isKnown(value: string): value is IconName {
    return (ICON_NAMES as readonly string[]).includes(value);
  }
}
`,
);

console.log(`sprite: ${names.length} icons`);

// Every `src: url(…)` in font.css, checked against the directory. A missing woff2 is a
// 404 the browser silently falls back from — degraded rather than broken, which is why
// this reports instead of exiting non-zero the way the icon checks do.
// Comments stripped first: the file documents the block to add by showing one, and a
// checker that reads its own instructions reports a face nobody declared.
const css = readFileSync(FONT_CSS, "utf8").replaceAll(/\/\*[\s\S]*?\*\//g, "");
const referenced = [...css.matchAll(/url\(["']?([^"')]+)["']?\)/g)].map((match) => match[1]);
const missing = referenced.filter(
  (href) => !existsSync(resolve(dirname(FONT_CSS), href.split("?")[0])),
);

console.log(`fonts: ${referenced.length} declared, ${referenced.length - missing.length} present`);
for (const href of missing) {
  console.warn(`  ! ${href} is declared in font.css and not in src/font/ — text will fall back`);
}
