// Everything this package takes from outside itself, in one place. No relative
// re-exports live here — that is what keeps it cycle-free.

// ── @loadbearing/content ─────────────────────────────────────────────────────
// A type and nothing else. Mail is composed per recipient, so a locale rides every mail
// request — and `content` sits left of this package, which is what makes the edge legal.
export type { Locale } from "@loadbearing/content";

// ── @loadbearing/contracts ───────────────────────────────────────────────────
export {
  type ActivityAction,
  ActivityActions,
  type ApiKeyId,
  type CreateDocPageInput,
  type CreateDocSpaceInput,
  type DocAccessOptionsDto,
  type DocAccessRuleDto,
  type DocGrantDto,
  type DocGrantKind,
  type DocGrantListDto,
  type DocImageType,
  type DocImageUploadDto,
  type DocNavNodeDto,
  type DocPageDraftDto,
  type DocPageId,
  type DocPageKind,
  type DocPageNodeDto,
  type DocPageRefInput,
  type DocPageStatus,
  type DocPageTreeDto,
  type DocReadingDto,
  type DocRevisionDto,
  type DocRevisionListDto,
  type DocRevisionRefInput,
  type DocSearchHitDto,
  type DocSearchHitsDto,
  type DocSpaceAudience,
  type DocSpaceDto,
  type DocSpaceId,
  type DocSpaceListDto,
  type DocSpaceNavDto,
  type DocSpaceNavInput,
  type DocSpaceRefInput,
  type DocTocEntryDto,
  type DomainEvent,
  type DomainEventInput,
  type DomainEventName,
  DomainEvents,
  type DomainId,
  type GoalId,
  type InvitationId,
  type InvitationLinkId,
  type KeysetQuery,
  type ListDocGrantsInput,
  type ListDocPagesInput,
  type ListNotificationsInput,
  type MailTemplateKey,
  type MailTemplateParams,
  MailTemplates,
  type MarkNotificationReadInput,
  type MoveDocPageInput,
  type NotificationCategory,
  type NotificationChannel,
  type NotificationDto,
  type NotificationId,
  type NotificationKind,
  type NotificationMode,
  type OrganizationId,
  type PaginationQuery,
  PROJECT_ROLES,
  type PreviewDocPageInput,
  type ProjectGrantId,
  type ProjectId,
  type ProjectRole,
  type PublishDocPageInput,
  type ReadDocPageInput,
  type RealtimeEventName,
  type RealtimeMessage,
  type RenderedDocDto,
  type RepositoryId,
  type RestoreDocRevisionInput,
  type RevokeDocGrantInput,
  type RoleId,
  type SaveDocGrantInput,
  type SaveDocPageInput,
  type SearchDocsInput,
  type TeamId,
  type UpdateDocSpaceInput,
  type UpdateNotificationPreferenceInput,
  type UploadDocImageInput,
  type UserId,
} from "@loadbearing/contracts";

// ── @loadbearing/core ────────────────────────────────────────────────────────
export { type Clock, ServerOnly, Token, Uuid } from "@loadbearing/core";

// ── @loadbearing/errors ──────────────────────────────────────────────────────
export {
  ConflictError,
  ForbiddenError,
  NotFoundError,
  type SchemaIssue,
  UnavailableError,
  ValidationError,
} from "@loadbearing/errors";
// A value, not a type: a subscriber builds an empty set to make a system principal
// that asserts nothing.
// ── @loadbearing/permissions ─────────────────────────────────────────────────
export {
  CapabilitySet,
  CORE_MODULE,
  EntitlementMask,
  type FlagKey,
  FlagRegistry,
  GATES,
  type ModuleKey,
  ModuleRegistry,
  type PermissionKey,
  PermissionRegistry,
  type ScopedSetDto,
} from "@loadbearing/permissions";
