"use client";

export {
  ActiveSessionList,
  type ActiveSessionListProps,
  ChangeEmailForm,
  type ChangeEmailFormProps,
  ChangePasswordForm,
  type ChangePasswordFormProps,
  LinkedAccountList,
  type LinkedAccountListProps,
  ProfileForm,
  type ProfileFormProps,
  TwoFactorPanel,
  type TwoFactorPanelProps,
  TwoFactorSetup,
  type TwoFactorSetupProps,
} from "./account/index.js";
export {
  ApiKeyList,
  type ApiKeyListProps,
  CreateApiKeyForm,
  useApiKeyFailure,
} from "./apikey/index.js";
export {
  ForgotPasswordForm,
  type ForgotPasswordFormProps,
  ResetPasswordForm,
  type ResetPasswordFormProps,
  type SessionOrganization,
  SessionProvider,
  type SessionProviderProps,
  type SessionUser,
  SignInForm,
  type SignInFormProps,
  SignOutButton,
  type SignOutButtonProps,
  SignUpForm,
  type SignUpFormProps,
  SocialSignIn,
  type SocialSignInProps,
  TwoFactorForm,
  type TwoFactorFormProps,
  useCapabilities,
  useFlags,
  useIsPlatformOrganization,
  useSession,
  VerifyEmailNotice,
  type VerifyEmailNoticeProps,
} from "./auth/index.js";
export {
  type DocAppearance,
  DocAppearancePanel,
  DocCopyButton,
  DocEditorForm,
  type DocEditorFormProps,
  DocGrantPanel,
  type DocGrantPanelProps,
  DocNavTree,
  DocPageTreeList,
  type DocPageTreeListProps,
  DocReaderPanel,
  type DocReaderPanelProps,
  DocRevisionList,
  type DocRevisionListProps,
  type DocSearchHit,
  DocSearchPanel,
  type DocSearchPanelProps,
  DocSpaceForm,
  type DocSpaceFormProps,
  DocSpaceList,
  type DocSpaceListProps,
  DocSpaceSwitcherButton,
  type RenderDocLink,
} from "./doc/index.js";
export { DocumentSearch, IndexDocumentForm } from "./document/index.js";
export { type ErrorMessage, useErrorMessage } from "./error/index.js";
export {
  MessageProvider,
  type MessageProviderProps,
  useMessages,
  useTranslator,
} from "./i18n/index.js";
export {
  InvitationList,
  type InvitationListProps,
  InviteMemberForm,
  MemberAccessPanel,
  type MemberAccessPanelProps,
  MemberCount,
  MemberList,
  type MemberListProps,
} from "./member/index.js";
export { ModuleNav, type ModuleNavProps } from "./nav/index.js";
export {
  NotificationBell,
  type NotificationBellProps,
  NotificationList,
  type NotificationListProps,
  NotificationPeek,
  type NotificationPeekProps,
  NotificationPreferenceForm,
} from "./notification/index.js";
export {
  CreateOrganizationForm,
  type CreateOrganizationFormProps,
  InvitationAccept,
  type InvitationAcceptProps,
  type InvitationPreview,
  OrganizationSwitcher,
  type OrganizationSwitcherProps,
} from "./organization/index.js";
export {
  AccountPanel,
  DeleteTenantPanel,
  FlagList,
  ModuleSwitchPanel,
  OrganizationEntitlementPanel,
  PlanForm,
  type PlanFormProps,
  PlanList,
  PlatformStatusPanel,
  ReplicaSwitchPanel,
  TenantExportPanel,
} from "./platform/index.js";
export {
  CreateRoleForm,
  EffectivePermissionsInspector,
  type EffectivePermissionsInspectorProps,
  type MatrixSubject,
  PermissionMatrix,
  type PermissionMatrixProps,
  PermissionOverrideForm,
  type PermissionOverrideFormProps,
  PermissionOverrideList,
  type PermissionOverrideListProps,
  RoleList,
  type RoleListProps,
  RoleMatrix,
  type RoleMatrixProps,
  useRoleFailure,
} from "./rbac/index.js";
