import { z } from "../import.js";
import { Identifiers } from "../primitive/index.js";

// Long enough for a paragraph, short enough that a row is one page read. A composer that
// needs more wants an attachment, which is a different feature.
const BODY_MAX = 4_000;

// Smaller than the keyset default: a message page is rendered all at once and each row
// is taller than a list row.
const PAGE_MAX = 50;

export class MessageContract {
  private constructor() {}

  public static readonly entity = z.object({
    id: Identifiers.messageId,
    conversationId: Identifiers.conversationId,
    authorId: Identifiers.userId,
    // Echoed back so the client can replace its optimistic row by the key it invented,
    // rather than by guessing which arriving message is the one it sent.
    clientId: z.uuid(),
    // Empty when `deleted`. The row survives so the conversation keeps its shape and
    // the keyset cursor over it stays stable.
    body: z.string(),
    deleted: z.boolean(),
    editedAt: z.date().nullable(),
    createdAt: z.date(),
  });

  // Its own query rather than `Keyset.query`: a message list pages **backwards** from
  // the newest, which is a different cursor direction and a different default size.
  public static readonly listQuery = z.object({
    conversationId: Identifiers.conversationId,
    limit: z.number().int().positive().max(PAGE_MAX).default(30),
    // Older than this cursor. Absent means the newest page, which is what a freshly
    // opened conversation wants.
    before: z.string().max(256).optional(),
  });

  // Its own page shape rather than `Keyset.page`, and the field name says which way it
  // goes: `nextCursor` would read as "newer", which is the opposite of what it means.
  public static readonly page = z.object({
    items: z.array(MessageContract.entity).readonly(),
    // Null is the start of the conversation. Not the same as an empty page: a full page
    // can still be the oldest one.
    olderCursor: z.string().nullable(),
  });

  public static readonly send = z.object({
    conversationId: Identifiers.conversationId,
    body: z.string().min(1).max(BODY_MAX),
    // The optimistic key **and** the dedupe key, generated by the client. A retried
    // send carries the same one and produces one row.
    clientId: z.uuid(),
  });

  public static readonly edit = z.object({
    conversationId: Identifiers.conversationId,
    messageId: Identifiers.messageId,
    createdAt: z.date(),
    body: z.string().min(1).max(BODY_MAX),
  });

  public static readonly remove = z.object({
    conversationId: Identifiers.conversationId,
    messageId: Identifiers.messageId,
    createdAt: z.date(),
  });

  // Stores nothing and returns nothing. Rate-limited in the use-case, because a
  // keystroke-per-signal composer would publish forty frames a sentence.
  public static readonly typing = z.object({ conversationId: Identifiers.conversationId });
}

export type MessageDto = z.infer<typeof MessageContract.entity>;
export type MessagePage = z.infer<typeof MessageContract.page>;
export type ListMessagesInput = z.infer<typeof MessageContract.listQuery>;
export type SendMessageInput = z.infer<typeof MessageContract.send>;
export type EditMessageInput = z.infer<typeof MessageContract.edit>;
export type DeleteMessageInput = z.infer<typeof MessageContract.remove>;
export type TypingInput = z.infer<typeof MessageContract.typing>;
